use std::{fs, path::PathBuf};
use chrono::Utc;
use serde_json::Value;
use super::{atomic::write_atomic, json_splice::{extract_top_level_member, replace_top_level_member}, snapshot::ClaudeSnapshot, CliLiveLogin, CliProvider};
#[derive(Clone)] pub struct ClaudePaths { pub credentials:PathBuf, pub claude_json:PathBuf }
impl ClaudePaths { pub fn resolve()->Result<Self,String>{let h=dirs::home_dir().ok_or_else(||"Could not resolve home directory".to_string())?;Ok(Self{credentials:h.join(".claude").join(".credentials.json"),claude_json:h.join(".claude.json")})} }
fn field(v:&Value,k:&str)->Option<String>{v.get(k).and_then(Value::as_str).map(str::to_string)}
pub fn needs_relogin(text:&str)->bool{serde_json::from_str::<Value>(text).ok().and_then(|v|v.get("claudeAiOauth")?.get("refreshTokenExpiresAt")?.as_i64()).map(|n|n<=Utc::now().timestamp_millis()).unwrap_or(false)}
pub fn read_live_identity(paths:&ClaudePaths)->CliLiveLogin {let blank=||CliLiveLogin{provider:CliProvider::Claude,present:false,email:None,identity_key:None,plan:None,org_name:None,matched_profile_id:None,error:None};if !paths.claude_json.is_file(){return blank();}let text=match fs::read_to_string(&paths.claude_json){Ok(v)=>v,Err(e)=>{let mut x=blank();x.error=Some(format!("Failed to read Claude identity: {e}"));return x;}};let value:Value=match serde_json::from_str(&text){Ok(v)=>v,Err(_)=>{let mut x=blank();x.error=Some("Failed to parse Claude identity".into());return x;}};let Some(account)=value.get("oauthAccount") else {return blank()};CliLiveLogin{provider:CliProvider::Claude,present:true,email:field(account,"emailAddress"),identity_key:field(account,"accountUuid"),plan:fs::read_to_string(&paths.credentials).ok().and_then(|s|serde_json::from_str::<Value>(&s).ok()).and_then(|v|field(v.get("claudeAiOauth")?,"subscriptionType")),org_name:field(account,"organizationName"),matched_profile_id:None,error:None}}
pub fn capture(paths:&ClaudePaths)->Result<(ClaudeSnapshot,CliLiveLogin),String>{let credentials=fs::read_to_string(&paths.credentials).map_err(|e|format!("Failed to read Claude credentials: {e}"))?;let json=fs::read_to_string(&paths.claude_json).map_err(|e|format!("Failed to read Claude settings: {e}"))?;let oauth=extract_top_level_member(&json,"oauthAccount").map_err(|e|format!("Failed to extract OAuth account: {e}"))?.ok_or_else(||"Claude OAuth account is missing".to_string())?.to_string();let live=read_live_identity(paths);Ok((ClaudeSnapshot{version:1,provider:CliProvider::Claude,captured_at:Utc::now().to_rfc3339(),credentials_text:credentials,oauth_account_text:oauth},live))}
pub fn restore(paths:&ClaudePaths,s:&ClaudeSnapshot)->Result<(),String>{serde_json::from_str::<Value>(&s.credentials_text).map_err(|_|"Claude snapshot credentials are invalid".to_string())?;let live=fs::read_to_string(&paths.claude_json).map_err(|e|format!("Failed to read Claude settings: {e}"))?;let replaced=replace_top_level_member(&live,"oauthAccount",&s.oauth_account_text).map_err(|_|"Claude settings are invalid; aborting without writes".to_string())?;write_atomic(&paths.credentials,s.credentials_text.as_bytes())?;write_atomic(&paths.claude_json,replaced.as_bytes())}
