//! On-demand wallpaper downloads.
//!
//! The 59 wallpapers used to be compiled into the frontend bundle, which cost
//! every install 31.9 MiB whether or not it ever showed one. Only the
//! thumbnails ship now; the full-resolution file is fetched the first time a
//! wallpaper is actually chosen and kept under the runtime directory, so a
//! test profile gets its own cache for free.
//!
//! What may be downloaded is pinned by the manifest compiled in below: the
//! caller names an id, never a URL or a path, and the bytes are only kept if
//! they hash to what the manifest says. A mismatch leaves the cache untouched.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::{Arc, OnceLock};
use std::time::Duration;
use tauri::{AppHandle, Emitter};
use tokio::sync::Mutex;
use uuid::Uuid;

/// Generated by `scripts/wallpapers/build_manifest.py`, and kept honest by
/// `tests/test_wallpaper_manifest_contract.py`.
const MANIFEST_JSON: &str = include_str!("../../../src/assets/wallpaper-manifest.json");

/// Where the pack is published. The tag lives in the manifest so that
/// re-pointing the app at a new pack is a tag bump, not 59 edits.
const PACK_RELEASE_BASE: &str = "https://github.com/miyafcos/mycmux-team/releases/download";

/// Well clear of the largest wallpaper in the pack (2.5 MiB), and small enough
/// that a redirect to something else cannot make us buffer a lot of memory.
const MAX_WALLPAPER_BYTES: usize = 8 * 1024 * 1024;

const DOWNLOAD_TIMEOUT: Duration = Duration::from_secs(60);

/// Payload: `{ id, receivedBytes, totalBytes, percent }`.
pub const DOWNLOAD_PROGRESS_EVENT: &str = "wallpaper-download-progress";

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct WallpaperEntry {
    pub id: String,
    pub filename: String,
    pub bytes: u64,
    pub sha256: String,
    pub width: u32,
    pub height: u32,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WallpaperManifest {
    pub pack_tag: String,
    pub wallpapers: Vec<WallpaperEntry>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CachedWallpaper {
    pub id: String,
    /// Absolute path; the frontend hands it to `convertFileSrc`.
    pub path: String,
    pub bytes: u64,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct WallpaperCacheState {
    pub directory: String,
    pub entries: Vec<CachedWallpaper>,
    pub total_bytes: u64,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct DownloadProgress {
    id: String,
    received_bytes: u64,
    total_bytes: u64,
    percent: u8,
}

fn manifest() -> Result<&'static WallpaperManifest, String> {
    static MANIFEST: OnceLock<Option<WallpaperManifest>> = OnceLock::new();
    MANIFEST
        .get_or_init(|| serde_json::from_str(MANIFEST_JSON).ok())
        .as_ref()
        .ok_or_else(|| "The bundled wallpaper manifest could not be parsed".to_string())
}

fn entry_for(id: &str) -> Result<&'static WallpaperEntry, String> {
    manifest()?
        .wallpapers
        .iter()
        .find(|entry| entry.id == id)
        .ok_or_else(|| format!("Unknown wallpaper id: {id}"))
}

/// Filenames come from the compiled-in manifest, so this can only fail if the
/// manifest itself is wrong — which is exactly the case worth refusing, since
/// the name is joined onto the cache directory.
fn is_safe_filename(filename: &str) -> bool {
    !filename.is_empty()
        && filename.len() <= 128
        && filename.ends_with(".webp")
        && !filename.starts_with('.')
        && filename
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-'))
}

fn resolve_download_url(pack_tag: &str, filename: &str) -> String {
    format!("{PACK_RELEASE_BASE}/{pack_tag}/{filename}")
}

pub fn cache_dir() -> Result<PathBuf, String> {
    Ok(crate::test_profile::runtime_dir()?.join("wallpapers"))
}

/// A cached file counts only when its size matches the manifest. A truncated
/// leftover therefore reads as "not downloaded" rather than being painted as a
/// broken image, and the next download overwrites it.
fn cache_state_at(directory: &Path) -> WallpaperCacheState {
    let mut entries = Vec::new();
    let mut total_bytes = 0u64;
    if let Ok(wallpapers) = manifest() {
        for entry in &wallpapers.wallpapers {
            if !is_safe_filename(&entry.filename) {
                continue;
            }
            let path = directory.join(&entry.filename);
            let Ok(metadata) = fs::metadata(&path) else {
                continue;
            };
            if !metadata.is_file() || metadata.len() != entry.bytes {
                continue;
            }
            total_bytes += metadata.len();
            entries.push(CachedWallpaper {
                id: entry.id.clone(),
                path: path.to_string_lossy().into_owned(),
                bytes: metadata.len(),
            });
        }
    }
    WallpaperCacheState {
        directory: directory.to_string_lossy().into_owned(),
        entries,
        total_bytes,
    }
}

fn cached_entry_at(directory: &Path, entry: &WallpaperEntry) -> Option<CachedWallpaper> {
    let path = directory.join(&entry.filename);
    let metadata = fs::metadata(&path).ok()?;
    if !metadata.is_file() || metadata.len() != entry.bytes {
        return None;
    }
    Some(CachedWallpaper {
        id: entry.id.clone(),
        path: path.to_string_lossy().into_owned(),
        bytes: metadata.len(),
    })
}

fn verify_payload(entry: &WallpaperEntry, payload: &[u8]) -> Result<(), String> {
    if payload.len() as u64 != entry.bytes {
        return Err(format!(
            "Downloaded wallpaper {} is {} bytes, expected {}",
            entry.id,
            payload.len(),
            entry.bytes
        ));
    }
    let digest = hex::encode(Sha256::digest(payload));
    if !digest.eq_ignore_ascii_case(&entry.sha256) {
        return Err(format!(
            "Downloaded wallpaper {} failed its checksum and was discarded",
            entry.id
        ));
    }
    Ok(())
}

/// Verifies first and writes second, through a temporary file, so a rejected
/// download leaves nothing behind and a killed process cannot leave a
/// half-written wallpaper under its real name.
fn store_payload_at(
    directory: &Path,
    entry: &WallpaperEntry,
    payload: &[u8],
) -> Result<CachedWallpaper, String> {
    if !is_safe_filename(&entry.filename) {
        return Err(format!("Unsafe wallpaper filename: {}", entry.filename));
    }
    verify_payload(entry, payload)?;
    fs::create_dir_all(directory)
        .map_err(|error| format!("Could not create the wallpaper cache: {error}"))?;
    let temporary = directory.join(format!(".tmp-{}", Uuid::new_v4()));
    fs::write(&temporary, payload)
        .map_err(|error| format!("Could not save the wallpaper: {error}"))?;
    let destination = directory.join(&entry.filename);
    if let Err(error) = fs::rename(&temporary, &destination) {
        let _ = fs::remove_file(&temporary);
        return Err(format!("Could not save the wallpaper: {error}"));
    }
    Ok(CachedWallpaper {
        id: entry.id.clone(),
        path: destination.to_string_lossy().into_owned(),
        bytes: entry.bytes,
    })
}

/// Removes only what this module writes — the manifest's filenames and its own
/// temporary files — so a cache directory that somehow holds anything else is
/// left alone rather than emptied.
fn clear_cache_at(directory: &Path) -> Result<u64, String> {
    let Ok(read_dir) = fs::read_dir(directory) else {
        return Ok(0);
    };
    let known: Vec<&str> = manifest()
        .map(|wallpapers| {
            wallpapers
                .wallpapers
                .iter()
                .map(|entry| entry.filename.as_str())
                .collect()
        })
        .unwrap_or_default();

    let mut freed = 0u64;
    for entry in read_dir.flatten() {
        let name = entry.file_name().to_string_lossy().into_owned();
        if !known.contains(&name.as_str()) && !name.starts_with(".tmp-") {
            continue;
        }
        let size = entry.metadata().map(|metadata| metadata.len()).unwrap_or(0);
        if fs::remove_file(entry.path()).is_ok() {
            freed += size;
        }
    }
    Ok(freed)
}

/// One lock per wallpaper id. A second request for the same wallpaper waits
/// here and then finds the file already cached, instead of fetching it twice.
fn download_locks() -> &'static Mutex<HashMap<String, Arc<Mutex<()>>>> {
    static LOCKS: OnceLock<Mutex<HashMap<String, Arc<Mutex<()>>>>> = OnceLock::new();
    LOCKS.get_or_init(|| Mutex::new(HashMap::new()))
}

async fn lock_for(id: &str) -> Arc<Mutex<()>> {
    let mut locks = download_locks().lock().await;
    locks.entry(id.to_string()).or_default().clone()
}

fn emit_progress(app: &AppHandle, id: &str, received: u64, total: u64) {
    let percent = if total == 0 {
        0
    } else {
        ((received.min(total) * 100) / total) as u8
    };
    let _ = app.emit(
        DOWNLOAD_PROGRESS_EVENT,
        DownloadProgress {
            id: id.to_string(),
            received_bytes: received,
            total_bytes: total,
            percent,
        },
    );
}

async fn fetch_wallpaper(app: &AppHandle, entry: &WallpaperEntry) -> Result<Vec<u8>, String> {
    let pack_tag = &manifest()?.pack_tag;
    let url = resolve_download_url(pack_tag, &entry.filename);
    let client = reqwest::Client::builder()
        .timeout(DOWNLOAD_TIMEOUT)
        .build()
        .map_err(|error| format!("Could not initialize the download client: {error}"))?;

    let mut response = client
        .get(&url)
        .send()
        .await
        .map_err(|error| format!("Could not reach the wallpaper pack: {error}"))?
        .error_for_status()
        .map_err(|error| format!("The wallpaper pack rejected the request: {error}"))?;

    if response
        .content_length()
        .is_some_and(|size| size > MAX_WALLPAPER_BYTES as u64)
    {
        return Err("The wallpaper is larger than the download limit".to_string());
    }

    let total = entry.bytes;
    let mut payload: Vec<u8> = Vec::with_capacity(total.min(MAX_WALLPAPER_BYTES as u64) as usize);
    let mut last_percent = u8::MAX;
    emit_progress(app, &entry.id, 0, total);

    while let Some(chunk) = response
        .chunk()
        .await
        .map_err(|error| format!("The wallpaper download was interrupted: {error}"))?
    {
        if payload.len() + chunk.len() > MAX_WALLPAPER_BYTES {
            return Err("The wallpaper is larger than the download limit".to_string());
        }
        payload.extend_from_slice(&chunk);
        let percent = if total == 0 {
            0
        } else {
            ((payload.len() as u64).min(total) * 100 / total) as u8
        };
        if percent != last_percent {
            last_percent = percent;
            emit_progress(app, &entry.id, payload.len() as u64, total);
        }
    }

    Ok(payload)
}

#[tauri::command(async)]
pub async fn get_wallpaper_cache_state() -> Result<WallpaperCacheState, String> {
    let directory = cache_dir()?;
    tokio::task::spawn_blocking(move || cache_state_at(&directory))
        .await
        .map_err(|error| format!("Could not read the wallpaper cache: {error}"))
}

#[tauri::command(async)]
pub async fn download_wallpaper(app: AppHandle, id: String) -> Result<CachedWallpaper, String> {
    let entry = entry_for(&id)?;
    let directory = cache_dir()?;

    let lock = lock_for(&id).await;
    let _guard = lock.lock().await;

    // Whoever waited on the lock gets the file the first caller fetched.
    let probe_directory = directory.clone();
    let probe_entry = entry.clone();
    if let Some(cached) = tokio::task::spawn_blocking(move || {
        cached_entry_at(&probe_directory, &probe_entry)
    })
    .await
    .map_err(|error| format!("Could not read the wallpaper cache: {error}"))?
    {
        emit_progress(&app, &id, cached.bytes, cached.bytes);
        return Ok(cached);
    }

    let payload = fetch_wallpaper(&app, entry).await?;
    let store_entry = entry.clone();
    tokio::task::spawn_blocking(move || store_payload_at(&directory, &store_entry, &payload))
        .await
        .map_err(|error| format!("Could not save the wallpaper: {error}"))?
}

#[tauri::command(async)]
pub async fn clear_wallpaper_cache() -> Result<u64, String> {
    let directory = cache_dir()?;
    tokio::task::spawn_blocking(move || clear_cache_at(&directory))
        .await
        .map_err(|error| format!("Could not clear the wallpaper cache: {error}"))?
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_entry(payload: &[u8]) -> WallpaperEntry {
        WallpaperEntry {
            id: "sample".to_string(),
            filename: "sample.webp".to_string(),
            bytes: payload.len() as u64,
            sha256: hex::encode(Sha256::digest(payload)),
            width: 10,
            height: 10,
        }
    }

    #[test]
    fn bundled_manifest_parses_and_every_entry_is_addressable() {
        let manifest = manifest().expect("the bundled manifest must parse");
        assert_eq!(manifest.wallpapers.len(), 59);
        assert!(!manifest.pack_tag.is_empty());

        let mut ids = std::collections::HashSet::new();
        let mut filenames = std::collections::HashSet::new();
        for entry in &manifest.wallpapers {
            assert!(ids.insert(entry.id.as_str()), "duplicate id {}", entry.id);
            assert!(
                filenames.insert(entry.filename.as_str()),
                "duplicate filename {}",
                entry.filename
            );
            assert!(
                is_safe_filename(&entry.filename),
                "unsafe filename {}",
                entry.filename
            );
            assert_eq!(entry.sha256.len(), 64, "bad digest for {}", entry.id);
            assert!(entry.sha256.chars().all(|c| c.is_ascii_hexdigit()));
            assert!(entry.bytes > 0 && entry.bytes <= MAX_WALLPAPER_BYTES as u64);
        }
    }

    #[test]
    fn unsafe_filenames_are_refused() {
        for filename in [
            "",
            "../escape.webp",
            "sub/dir.webp",
            ".hidden.webp",
            "no-extension",
            "spaced name.webp",
        ] {
            assert!(!is_safe_filename(filename), "{filename} should be refused");
        }
        assert!(is_safe_filename("macos_monterey.webp"));
    }

    #[test]
    fn the_download_url_is_built_from_the_pack_tag() {
        assert_eq!(
            resolve_download_url("wallpapers-v1", "macos_monterey.webp"),
            "https://github.com/miyafcos/mycmux-team/releases/download/wallpapers-v1/macos_monterey.webp"
        );
        // Changing the tag is the whole re-pointing mechanism.
        assert!(resolve_download_url("wallpapers-v2", "koi.webp").contains("wallpapers-v2"));
    }

    #[test]
    fn a_checksum_mismatch_is_never_stored() {
        let directory = tempfile::tempdir().unwrap();
        let entry = sample_entry(b"the real wallpaper bytes");

        // Same length as the real payload, so this exercises the digest check
        // rather than falling out at the size check above it.
        let tampered = b"tampered wallpaper bytes";
        assert_eq!(tampered.len() as u64, entry.bytes);
        let error = store_payload_at(directory.path(), &entry, tampered)
            .expect_err("a mismatched payload must be refused");
        assert!(error.contains("checksum"), "unexpected error: {error}");
        assert!(
            !directory.path().join(&entry.filename).exists(),
            "the wallpaper must not be written when the checksum fails"
        );
        // Nor may the temporary file survive.
        assert_eq!(fs::read_dir(directory.path()).unwrap().count(), 0);
    }

    #[test]
    fn a_truncated_payload_is_never_stored() {
        let directory = tempfile::tempdir().unwrap();
        let entry = sample_entry(b"the real wallpaper bytes");
        let error = store_payload_at(directory.path(), &entry, b"the real wallpaper")
            .expect_err("a short payload must be refused");
        assert!(error.contains("expected"), "unexpected error: {error}");
        assert!(!directory.path().join(&entry.filename).exists());
    }

    #[test]
    fn a_matching_payload_is_stored_and_reported_as_cached() {
        let directory = tempfile::tempdir().unwrap();
        let payload = b"the real wallpaper bytes";
        let entry = sample_entry(payload);

        let stored = store_payload_at(directory.path(), &entry, payload).unwrap();
        assert_eq!(stored.id, "sample");
        assert_eq!(stored.bytes, payload.len() as u64);
        assert_eq!(
            fs::read(directory.path().join(&entry.filename)).unwrap(),
            payload
        );
        assert!(cached_entry_at(directory.path(), &entry).is_some());
    }

    #[test]
    fn a_wrong_sized_leftover_reads_as_not_downloaded() {
        let directory = tempfile::tempdir().unwrap();
        let entry = sample_entry(b"the real wallpaper bytes");
        fs::write(directory.path().join(&entry.filename), b"half").unwrap();
        assert!(cached_entry_at(directory.path(), &entry).is_none());
    }

    #[test]
    fn an_empty_cache_lists_nothing() {
        let directory = tempfile::tempdir().unwrap();
        let state = cache_state_at(directory.path());
        assert!(state.entries.is_empty());
        assert_eq!(state.total_bytes, 0);
    }

    #[test]
    fn a_missing_cache_directory_is_not_an_error() {
        let directory = tempfile::tempdir().unwrap();
        let absent = directory.path().join("never-created");
        assert!(cache_state_at(&absent).entries.is_empty());
        assert_eq!(clear_cache_at(&absent).unwrap(), 0);
    }

    #[test]
    fn clearing_removes_downloads_and_temporaries_but_nothing_else() {
        let directory = tempfile::tempdir().unwrap();
        let known = &manifest().unwrap().wallpapers[0];
        fs::write(directory.path().join(&known.filename), vec![0u8; 16]).unwrap();
        fs::write(directory.path().join(".tmp-abandoned"), vec![0u8; 4]).unwrap();
        fs::write(directory.path().join("notes.txt"), b"keep me").unwrap();

        assert_eq!(clear_cache_at(directory.path()).unwrap(), 20);
        assert!(!directory.path().join(&known.filename).exists());
        assert!(!directory.path().join(".tmp-abandoned").exists());
        assert!(directory.path().join("notes.txt").exists());
    }

    #[test]
    fn only_manifest_ids_can_be_requested() {
        assert!(entry_for("macos_monterey").is_ok());
        for id in ["", "../../secret", "unknown_wallpaper"] {
            assert!(entry_for(id).is_err(), "{id} should not resolve");
        }
    }
}
