//! Only trusted preview anchor clicks can reach the native opener.
use base64::Engine;
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock};
use std::time::{Duration, Instant};
use tauri::{AppHandle, Url};

const MAX_URL_BYTES: usize = 16_384;
const MAX_PATH_BYTES: usize = 8_192;
const CLICK_INTERVAL: Duration = Duration::from_millis(500);
const CLICK_HOST: &str = "mycmux-preview-link.invalid";

pub(super) struct ClickGate {
    token: String,
    sequences: HashMap<String, u64>,
    last_open: Option<Instant>,
}

impl ClickGate {
    pub(super) fn new() -> Self {
        Self {
            token: uuid::Uuid::new_v4().simple().to_string(),
            sequences: HashMap::new(),
            last_open: None,
        }
    }

    pub(super) fn script(&self) -> String {
        include_str!("webpane_preview_links.js").replace("__MYCMUX_PREVIEW_TOKEN__", &self.token)
    }

    /// The random capability lives only in the document-start listener's closure.
    /// A document cannot supply it through a public command or a mutable global.
    pub(super) fn consume(&mut self, url: &Url, now: Instant) -> Option<Result<String, String>> {
        if url.host_str() != Some(CLICK_HOST) {
            return None;
        }
        let reject = || Some(Err("preview click capability is invalid".to_string()));
        if url.scheme() != "https"
            || url.port().is_some()
            || !url.username().is_empty()
            || url.password().is_some()
            || url.fragment().is_some()
            || url.as_str().len() > MAX_URL_BYTES * 3 + 256
        {
            return reject();
        }
        let parts: Vec<_> = url.path_segments().into_iter().flatten().collect();
        if parts.len() != 3
            || parts[0].len() != 32
            || !parts[0].bytes().all(|byte| byte.is_ascii_hexdigit())
            || parts[2].len() != 64
        {
            return reject();
        }
        let Ok(sequence) = parts[1].parse::<u64>() else {
            return reject();
        };
        let previous = self.sequences.get(parts[0]).copied().unwrap_or(0);
        if sequence == 0
            || parts[1] != sequence.to_string()
            || previous.checked_add(1) != Some(sequence)
        {
            return reject();
        }
        let query: Vec<_> = url.query_pairs().collect();
        if query.len() != 1 || query[0].0 != "url" || query[0].1.len() > MAX_URL_BYTES {
            return reject();
        }
        // Navigation events may expose a destination URL to the document.
        // A proof for one target cannot authorize another target or sequence.
        let message = format!("{}\n{sequence}\n{}", parts[0], query[0].1);
        let expected = click_mac(&self.token, &message);
        let difference = expected
            .as_bytes()
            .iter()
            .zip(parts[2].as_bytes())
            .fold(0u8, |difference, (left, right)| difference | (left ^ right));
        if difference != 0 {
            return reject();
        }
        // Consume even a throttled or malformed target so it cannot be replayed.
        self.sequences.insert(parts[0].to_string(), sequence);
        if self
            .last_open
            .is_some_and(|last| now.saturating_duration_since(last) < CLICK_INTERVAL)
        {
            return Some(Err("preview link click was rate limited".into()));
        }
        self.last_open = Some(now);
        Some(Ok(query[0].1.to_string()))
    }
}

/// HMAC-SHA256 with the fixed short key already generated by ClickGate.
/// The existing sha2 dependency supplies SHA-256; no new crate is needed.
fn click_mac(key: &str, message: &str) -> String {
    assert!(key.len() <= 64);
    let mut inner = [0x36u8; 64];
    let mut outer = [0x5cu8; 64];
    for (index, byte) in key.bytes().enumerate() {
        inner[index] ^= byte;
        outer[index] ^= byte;
    }
    let mut digest = Sha256::new();
    digest.update(inner);
    digest.update(message.as_bytes());
    let inner_digest = digest.finalize();
    let mut digest = Sha256::new();
    digest.update(outer);
    digest.update(inner_digest);
    digest
        .finalize()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

#[derive(Debug, PartialEq)]
enum PreviewTarget {
    Reveal(PathBuf),
    Browser(Url),
}

fn decode_mzopen(url: &str) -> Result<String, String> {
    if url.len() > MAX_URL_BYTES || !url.starts_with("mzopen:b64.") {
        return Err("mzopen requires mzopen:b64.<base64url> within the size limit".into());
    }
    let encoded = &url[11..];
    if encoded.is_empty()
        || !encoded
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
    {
        return Err("mzopen requires unpadded base64url".into());
    }
    let bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
        .decode(encoded)
        .map_err(|_| "mzopen contains invalid base64url")?;
    if bytes.is_empty() || bytes.len() > MAX_PATH_BYTES {
        return Err("mzopen path is empty or exceeds the size limit".into());
    }
    String::from_utf8(bytes).map_err(|_| "mzopen path is not UTF-8".into())
}

fn validate_plain_path(path: &str, allow_posix: bool) -> Result<(), String> {
    if path
        .chars()
        .any(|ch| ch.is_control() || matches!(ch, '"' | '<' | '>' | '|' | '*' | '?'))
    {
        return Err("mzopen path contains forbidden characters".into());
    }
    let bytes = path.as_bytes();
    let drive = bytes.len() >= 3
        && bytes[0].is_ascii_alphabetic()
        && bytes[1] == b':'
        && matches!(bytes[2], b'/' | b'\\');
    let unc =
        path.starts_with("\\\\") && !path.starts_with("\\\\.\\") && !path.starts_with("\\\\?\\");
    let posix = allow_posix && path.starts_with('/') && !path.starts_with("//");
    if !drive && !unc && !posix {
        return Err("mzopen requires an absolute drive, UNC, or native POSIX path".into());
    }
    let tail = if drive { &path[2..] } else { path };
    if tail.contains(':') {
        return Err("mzopen path contains a protocol or alternate data stream".into());
    }
    let components: Vec<_> = tail
        .split(['/', '\\'])
        .filter(|part| !part.is_empty())
        .collect();
    if unc && (components.len() < 2 || path[2..].starts_with(['/', '\\'])) {
        return Err("mzopen UNC path requires a server and share".into());
    }
    for part in components {
        if part == "." || part == ".." || (!posix && part.ends_with([' ', '.'])) {
            return Err("mzopen path contains traversal or ambiguous components".into());
        }
        if !posix {
            let stem = part
                .split('.')
                .next()
                .unwrap_or_default()
                .to_ascii_uppercase();
            if matches!(
                stem.as_str(),
                "CON" | "PRN" | "AUX" | "NUL" | "CONIN$" | "CONOUT$"
            ) || stem.len() == 4
                && (stem.starts_with("COM") || stem.starts_with("LPT"))
                && matches!(stem.as_bytes()[3], b'1'..=b'9')
            {
                return Err("mzopen path names a device".into());
            }
        }
    }
    Ok(())
}

fn parse_target_with(
    url: &str,
    allow_posix: bool,
    existing: impl FnOnce(&Path) -> bool,
) -> Result<PreviewTarget, String> {
    if url.len() > MAX_URL_BYTES || url.chars().any(char::is_control) {
        return Err("preview link exceeds the size limit or contains controls".into());
    }
    if url.starts_with("mzopen:") {
        let decoded = decode_mzopen(url)?;
        validate_plain_path(&decoded, allow_posix)?;
        let path = PathBuf::from(decoded);
        if !existing(&path) {
            return Err("mzopen target is not an existing file or directory".into());
        }
        return Ok(PreviewTarget::Reveal(path));
    }
    // Do not let URL parsing repair backslashes, whitespace, or a missing authority.
    let lower = url.to_ascii_lowercase();
    if (!lower.starts_with("http://") && !lower.starts_with("https://"))
        || url.contains('\\')
        || url.trim() != url
    {
        return Err("preview links accept only mzopen and http(s)".into());
    }
    let parsed = Url::parse(url).map_err(|_| "preview link URL is invalid")?;
    if !matches!(parsed.scheme(), "http" | "https")
        || parsed.host_str().is_none()
        || parsed.host_str() == Some("asset.localhost")
        || parsed.host_str() == Some(CLICK_HOST)
    {
        return Err("preview link requires an external http(s) host".into());
    }
    Ok(PreviewTarget::Browser(parsed))
}

pub(super) fn retains_mzopen_href(url: &str) -> bool {
    // Rendering checks syntax only; disk/network existence is checked after a click.
    decode_mzopen(url)
        .and_then(|path| validate_plain_path(&path, cfg!(unix)))
        .is_ok()
}

fn parse_target(url: &str) -> Result<PreviewTarget, String> {
    parse_target_with(url, cfg!(unix), |path| {
        path.is_absolute()
            && std::fs::metadata(path).is_ok_and(|metadata| metadata.is_file() || metadata.is_dir())
    })
}

pub(super) async fn open(app: AppHandle, url: String) -> Result<(), String> {
    crate::util::task::run_blocking("preview_link_open", move || {
        let target = parse_target(&url)?;
        match target {
            PreviewTarget::Reveal(path) => {
                let canonical = dunce::canonicalize(&path)
                    .map_err(|error| format!("mzopen target: {error}"))?;
                let kind = if canonical.is_dir() {
                    "open-directory"
                } else {
                    "reveal-file"
                };
                if super::record_preview_link(kind, &canonical.to_string_lossy())? {
                    return Ok(());
                }
                // Never open the file with its application or pass a shell verb.
                super::super::fs::reveal_path_in_os_file_manager(&canonical)
            }
            PreviewTarget::Browser(url) => {
                if super::record_preview_link("browser", url.as_str())? {
                    return Ok(());
                }
                use tauri_plugin_shell::ShellExt;
                #[allow(deprecated)]
                app.shell()
                    .open(url.as_str(), None)
                    .map_err(|error| format!("preview browser open: {error}"))
            }
        }
    })
    .await
}

pub(super) fn throttle_primary(label: &str) -> Result<(), String> {
    static LAST_OPENS: OnceLock<Mutex<HashMap<String, Instant>>> = OnceLock::new();
    let mut opens = LAST_OPENS
        .get_or_init(|| Mutex::new(HashMap::new()))
        .lock()
        .map_err(|_| "preview click gate failed")?;
    let now = Instant::now();
    if opens
        .get(label)
        .is_some_and(|last| now.duration_since(*last) < CLICK_INTERVAL)
    {
        return Err("preview link click was rate limited".into());
    }
    opens.insert(label.to_string(), now);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn encoded(bytes: &[u8]) -> String {
        format!(
            "mzopen:b64.{}",
            base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(bytes)
        )
    }

    #[test]
    fn mzopen_accepts_existing_drive_unc_and_native_paths() {
        for path in [
            r"C:\reports\file.txt",
            "C:/reports/folder",
            r"\\server\share\file.txt",
            "C:/reports/\u{65e5}\u{672c}\u{8a9e} file.txt",
        ] {
            assert_eq!(
                parse_target_with(&encoded(path.as_bytes()), false, |_| true).unwrap(),
                PreviewTarget::Reveal(PathBuf::from(path))
            );
        }
        assert!(parse_target_with(&encoded(b"/Users/test/report.txt"), true, |_| true).is_ok());
        assert!(parse_target_with(&encoded(b"/Users/test/report.txt"), false, |_| true).is_err());
    }

    #[test]
    fn mzopen_checks_actual_file_directory_and_missing_targets() {
        let file = std::env::current_exe().unwrap();
        let directory = file.parent().unwrap();
        for path in [file.as_path(), directory] {
            let plain = dunce::canonicalize(path).unwrap();
            assert!(matches!(
                parse_target(&encoded(plain.to_str().unwrap().as_bytes())),
                Ok(PreviewTarget::Reveal(_))
            ));
        }
        let missing = directory.join(format!("missing-preview-link-{}", uuid::Uuid::new_v4()));
        assert!(parse_target(&encoded(missing.to_str().unwrap().as_bytes())).is_err());
    }

    #[test]
    fn mzopen_rejects_malformed_base64_utf8_and_size_limits() {
        for url in [
            "mzopen:b64.",
            "mzopen:b64.A",
            "mzopen:b64.A!A",
            "mzopen:b64.YQ==",
            "mzopen:b64.Zh",
            "mzopen://b64.YQ",
            "mzopen:b64.YQ/",
            "mzopen:b64.YQ?x",
            "mzopen:b64.YQ#x",
        ] {
            assert!(parse_target_with(url, false, |_| true).is_err(), "{url}");
        }
        assert!(parse_target_with(&encoded(&[0xff, 0xfe]), false, |_| true).is_err());
        assert!(parse_target_with(
            &format!("mzopen:b64.{}", "a".repeat(MAX_URL_BYTES)),
            false,
            |_| true
        )
        .is_err());
        assert!(parse_target_with(
            &encoded(format!("C:/{}", "x".repeat(MAX_PATH_BYTES)).as_bytes()),
            false,
            |_| true
        )
        .is_err());
    }

    #[test]
    fn mzopen_rejects_relative_missing_traversal_devices_and_arguments() {
        for path in [
            "report.txt",
            "C:report.txt",
            "C:/a/../report.txt",
            "C:/a/./report.txt",
            r"C:\a\..\b",
            r"\\server",
            r"\\?\C:\a",
            r"\\.\PIPE\a",
            "C:/a:stream",
            "C:/a\" /select,",
            "C:/a\0b",
            "C:/a\nb",
            "C:/CON.txt",
            "C:/COM1",
            "C:/folder.",
            "C:/folder ",
            "shell:Downloads",
            "https://example.test/a",
            "//server/share",
            r"\\server\share:argument",
        ] {
            assert!(
                parse_target_with(&encoded(path.as_bytes()), false, |_| true).is_err(),
                "{path:?}"
            );
        }
        assert!(parse_target_with(&encoded(b"C:/missing/file.txt"), false, |_| false).is_err());
        assert!(
            parse_target_with(&encoded(br"\\missing\share\file.txt"), false, |_| false).is_err()
        );
    }

    #[test]
    fn external_links_only_accept_http_and_https() {
        for url in [
            "http://example.test/x",
            "https://example.test/x",
            "HTTPS://example.test/x",
        ] {
            assert!(matches!(
                parse_target_with(url, false, |_| false),
                Ok(PreviewTarget::Browser(_))
            ));
        }
        for url in [
            "ms-settings:display",
            "file:///C:/Windows/cmd.exe",
            "mailto:a@example.test",
            "tel:123",
            "javascript:alert(1)",
            "http:example.test",
            "https:\\example.test",
            "https://",
            "https://example.test/\n",
            "http://asset.localhost/a",
            "https://mycmux-preview-link.invalid/a",
        ] {
            assert!(parse_target_with(url, false, |_| true).is_err(), "{url}");
        }
    }

    #[test]
    fn click_capability_is_private_sequenced_and_rate_limited() {
        let mut gate = ClickGate::new();
        let url = |token: &str, doc: &str, seq: u64| {
            let message = format!("{doc}\n{seq}\nhttps://example.test/x");
            let proof = click_mac(token, &message);
            Url::parse(&format!(
                "https://{CLICK_HOST}/{doc}/{seq}/{proof}?url=https%3A%2F%2Fexample.test%2Fx"
            ))
            .unwrap()
        };
        let token = gate.token.clone();
        let doc = "0123456789abcdef0123456789abcdef";
        let now = Instant::now();
        assert!(gate.consume(&url("wrong", doc, 1), now).unwrap().is_err());
        assert!(gate.consume(&url(&token, doc, 1), now).unwrap().is_ok());
        assert!(gate
            .consume(&url(&token, doc, 1), now + CLICK_INTERVAL)
            .unwrap()
            .is_err());
        assert!(gate.consume(&url(&token, doc, 2), now).unwrap().is_err());
        assert!(gate
            .consume(&url(&token, doc, 3), now + CLICK_INTERVAL)
            .unwrap()
            .is_ok());
        assert!(gate
            .consume(
                &url(&token, "abcdef0123456789abcdef0123456789", 1),
                now + CLICK_INTERVAL * 2
            )
            .unwrap()
            .is_ok());
        assert!(gate
            .consume(&Url::parse("https://example.test/x").unwrap(), now)
            .is_none());
    }

    #[test]
    fn click_mac_matches_the_rfc_4231_sha256_vector() {
        assert_eq!(
            click_mac("Jefe", "what do ya want for nothing?"),
            "5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843"
        );
    }

    #[test]
    fn signed_clicks_continue_working_across_many_reloaded_documents() {
        let mut gate = ClickGate::new();
        let now = Instant::now();
        for index in 0..160u32 {
            let doc = format!("{index:032x}");
            let proof = click_mac(&gate.token, &format!("{doc}\n1\nhttps://example.test/x"));
            let url = Url::parse(&format!(
                "https://{CLICK_HOST}/{doc}/1/{proof}?url=https%3A%2F%2Fexample.test%2Fx"
            ))
            .unwrap();
            assert!(gate
                .consume(&url, now + CLICK_INTERVAL * index)
                .unwrap()
                .is_ok());
        }
    }

    #[test]
    fn captured_click_proof_cannot_authorize_another_target_or_sequence() {
        let mut gate = ClickGate::new();
        let doc = "0123456789abcdef0123456789abcdef";
        let proof = click_mac(&gate.token, &format!("{doc}\n1\nhttps://example.test/x"));
        let captured =
            format!("https://{CLICK_HOST}/{doc}/1/{proof}?url=https%3A%2F%2Fexample.test%2Fx");
        let now = Instant::now();
        let different_target = captured.replace("%2Fx", "%2Fforged");
        let different_sequence = captured.replace("/1/", "/2/");
        assert!(gate
            .consume(&Url::parse(&different_target).unwrap(), now)
            .unwrap()
            .is_err());
        assert!(gate
            .consume(&Url::parse(&different_sequence).unwrap(), now)
            .unwrap()
            .is_err());
        assert!(gate
            .consume(&Url::parse(&captured).unwrap(), now)
            .unwrap()
            .is_ok());
        assert!(gate
            .consume(&Url::parse(&captured).unwrap(), now + CLICK_INTERVAL)
            .unwrap()
            .is_err());
        assert!(gate
            .consume(
                &Url::parse(&different_sequence).unwrap(),
                now + CLICK_INTERVAL
            )
            .unwrap()
            .is_err());
        assert!(!captured.contains(&gate.token));
    }

    #[test]
    fn test_recorder_never_activates_without_a_profile() {
        assert!(!super::super::preview_link_recording_enabled(
            false,
            Some("1")
        ));
        assert!(!super::super::preview_link_recording_enabled(true, None));
        assert!(!super::super::preview_link_recording_enabled(
            true,
            Some("true")
        ));
        assert!(super::super::preview_link_recording_enabled(
            true,
            Some("1")
        ));
    }
}
