// 設定 → ランチャー タブの文言 (2026-09-05)。
// LauncherTab.tsx 側は非 ASCII を持たず、文言はここに集約する
// (launcherStrings.ts / webPaneStrings と同じ方針 — 委譲先の文字化け防止)。
export const launcherTabStrings = {
  launchHeading: "新規に起動",
  webHeading: "Web",
  resumeRow: "続きから",
  resumeNote: "このPCの履歴から再開する行。中身の絞り込みは「このPCの履歴から再開」タブと共通",

  // ── フォルダ (登録済み) ──
  foldersHeading: "フォルダ",
  foldersNote: "登録済み。手動は並べ替え可、自動は新しい順",
  sectionCount: (total: number, manual: number, auto: number) =>
    `${total} 件 (手動 ${manual}・自動 ${auto})`,
  showSection: "表示",
  editLabelTooltip: "クリックで表示名を編集",
  pickFolder: "フォルダを選んで登録…",
  pickFolderTitle: "ランチャーに登録するフォルダ",
  sectionEmpty: "登録がありません。フォルダを選んで登録してください",
  badgeManual: "手動",
  badgeAuto: "自動",
  moveUp: "上へ",
  moveDown: "下へ",
  pin: "固定",
  pinTooltip: "手動に昇格させ、走査で消えないようにする",
  remove: "削除",
  ignore: "無視",
  ignoreTooltip: "この場所を候補・自動から外す (詳細で解除できる)",
  missing: "見つかりません",
  markLegend: "印: ●MM/DD = 自分のセッションで触れた / MM/DD = リポジトリやファイルの更新。手動には印が付かない。",
  alreadyRegistered: (section: string) => `すでに「${section}」に登録されています`,
  notADirectory: "フォルダが見つかりません",
  labelEmpty: "表示名が空です",

  // ── 詳細 ──
  detailsHeading: "詳細",
  jsonLabel: "正本",
  rootsLabel: "bash 用",
  rootsWrittenAt: (when: string) => `(書き出し ${when})`,
  rootsNeverWritten: "(未書き出し)",
  exportNow: "今すぐ書き出す",
  open: "開く",
  externalMerged: (when: string) => `launch-roots.txt の外部変更を取り込みました (${when})`,
  ignoredHeading: "無視",
  ignoredEmpty: "無視している場所はありません",
  unignore: "解除",
  saveFailed: (reason: string) => `保存できませんでした: ${reason}`,
  loading: "読み込み中…",

  // ── 候補 (Phase 2) ──
  candidatesHeading: "候補",
  candidatesNote: "見つかったが未登録のフォルダ。押した分だけ登録される",
  refreshCandidates: "候補を更新",
  scanning: "走査中…",
  lastScan: (when: string) => `最終走査 ${when}`,
  lastScanNever: "まだ走査していません",
  scanTruncated: "上限で打ち切り",
  scanFailed: (rule: string, reason: string) => `${rule}: ${reason}`,
  noCandidates: "候補はありません",
  moreCandidates: (n: number) => `さらに ${n} 件`,
  registerTo: (section: string) => `${section}に登録`,
  signalGit: (date: string) => `git 活動 ${date}`,
  signalFolder: (date: string) => `更新 ${date}`,
  signalSession: (date: string) => `セッション ${date}`,
  signalMention: (date: string) => `セッションで触れた ${date}`,
  signalMru: "最近使った",

  // ── 自動登録 (Phase 2) ──
  rulesHeading: "自動登録",
  rulesNote: "ルールが走査して候補にする / そのまま登録する",
  ruleTypeGit: "git リポジトリ",
  ruleTypeFolder: "ファイル更新",
  ruleTypeSessionCwd: "動かした場所",
  ruleTypeMentions: "セッションで触れた",
  ruleTypeGitNote: "親フォルダ直下の git リポジトリのうち、最近活動があったもの",
  ruleTypeFolderNote: "根の下を歩き、最近ファイル更新があった枝を代表階層で束ねる",
  ruleTypeSessionCwdNote: "エージェントを動かした作業フォルダ (走査なし・ailog から読む)",
  ruleTypeMentionsNote: "セッション本文で根の配下のパスに触れた回数が多い枝",
  ruleTypeUnknown: "不明な種類 (このバージョンでは走査しない)",
  modeSuggest: "候補にする",
  modeAuto: "自動で登録する",
  ruleEnabled: "有効",
  editRule: "編集",
  deleteRule: "削除",
  deleteRuleNote: "このルールが自動で登録した行も消えます (残したい行は先に固定してください)",
  addRule: "ルールを追加",
  scanNow: "今すぐ走査",
  scheduleNote: "起動 15 秒後 (前回から 3 時間以上なら) と 3 時間おきに自動で走査します",
  scheduleOffInTest: "テストプロファイルでは自動走査を止めています (「今すぐ走査」だけ効きます)",
  noRules: "ルールがありません",
  summaryDays: (n: number) => `${n} 日`,
  summaryMax: (n: number) => `上限 ${n}`,
  summaryUnder: (paths: string) => `${paths} の直下`,
  summaryDepth: (depth: number, overrides: string) => (overrides ? `階層 ${depth} (${overrides})` : `階層 ${depth}`),
  summaryMinMentions: (n: number) => `${n} 回以上`,
  summaryMinSessions: (n: number) => `${n} 件以上`,
  summaryExcludes: (n: number) => `除外 ${n} 語`,
  summaryAllSessions: "すべてのセッション",

  // ── ルール編集フォーム (Phase 2) ──
  editorTitleNew: "ルールを追加",
  editorTitleEdit: "ルールを編集",
  fieldSection: "セクション",
  fieldType: "種類",
  fieldMode: "動作",
  fieldParents: "親フォルダ (1 行 1 つ)",
  fieldRoot: "根のフォルダ",
  fieldRootOptional: "根のフォルダ (空ならすべて)",
  fieldWindowDays: "何日以内",
  fieldMax: "上限 (件)",
  fieldDepth: "代表階層",
  fieldDepthOverrides: "階層の上書き (例: 駿台=3・1 行 1 つ)",
  fieldMaxDepth: "走査の深さ上限",
  fieldMinMentions: "言及回数の下限",
  fieldMinSessions: "セッション数の下限",
  fieldExcludePrefixes: "除外する先頭文字 (1 行 1 つ)",
  fieldExcludeNames: "除外するフォルダ名 (1 行 1 つ)",
  fieldExcludeSubstrings: "除外する部分文字列 (1 行 1 つ)",
  fieldTopLevelExclude: "根の直下で除外する名前 (1 行 1 つ)",
  pickFolderForRule: "選ぶ…",
  addFolderToList: "追加",
  saveRule: "保存",
  cancelEdit: "やめる",
  validationRootRequired: "根のフォルダを指定してください",
  validationParentsRequired: "親フォルダを 1 つ以上指定してください",
  validationPositiveInteger: (field: string) => `${field} は 1 以上の整数にしてください`,
  validationNotADirectory: (path: string) => `フォルダが見つかりません: ${path}`,
  validationAbsolutePath: (path: string) => `絶対パスで指定してください: ${path}`,
  validationLineBreakInPath: "パスに改行は使えません",
} as const;
