import { memo } from "react";
import type { FindingKind, FindingsReport, ReworkRankingsReport, RuleCheckFinding, RuleCheckReport } from "../../lib/ailog";
import { ButtonGroup, Chip, EmptyState, ScrollBox, Section, SkeletonBlock, noteStyle, subtleButtonStyle, tableStyle, tdLeftStyle, tdStyle, thLeftStyle, thStyle } from "./ui";

const KIND_OPTIONS: { value: FindingKind | "all"; label: string }[] = [{ value: "all", label: "すべて" }, { value: "cause", label: "原因" }, { value: "constraint", label: "制約" }, { value: "gotcha", label: "ハマり" }, { value: "decision", label: "決めた" }, { value: "verified", label: "確かめた" }];
const KIND_LABELS: Record<FindingKind, string> = { cause: "原因", constraint: "制約", gotcha: "ハマり", decision: "決めた", verified: "確かめた" };
const trapKinds: FindingKind[] = ["gotcha", "cause"];
const decisionKinds: FindingKind[] = ["decision", "constraint", "verified"];

export const LearningView = memo(function LearningView({ findings, rankings, rules, kind, query, loading, error, onKindChange, onQueryChange, onLoadMore, onOpenDetail, onOpenRecord, onCopyRule, hasMore }: {
  findings: FindingsReport | null; rankings: ReworkRankingsReport | null; rules: RuleCheckReport | null; kind: FindingKind | null; query: string; loading: boolean; error: string | null;
  onKindChange: (kind: FindingKind | null) => void; onQueryChange: (query: string) => void; onLoadMore: () => void; onOpenDetail: (kind: string, sessionId: string) => void; onOpenRecord: (date: number) => void; onCopyRule: (text: string) => void; hasMore?: boolean;
}) {
  const rows = findings?.rows ?? [];
  const filtered = kind ? rows.filter((row) => row.kind === kind) : rows;
  return <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
    <div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" }}><ButtonGroup options={KIND_OPTIONS} value={kind ?? "all"} onChange={(value) => onKindChange(value === "all" ? null : value)} ariaLabel="学びの分類" /><input aria-label="検索" type="search" value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="検索" style={searchStyle} /></div>
    {error ? <EmptyState kind="error" message={error} /> : loading && !findings ? <SkeletonBlock height={140} label="更新中…" /> : <>
      <FindingSection title="罠" rows={filtered.filter((row) => trapKinds.includes(row.kind))} onOpenDetail={onOpenDetail} onOpenRecord={onOpenRecord} onCopyRule={onCopyRule} />
      <Section title="失敗コマンド上位" actions={<Chip>数えた</Chip>}><RankingTable headers={["コマンド", "実行", "失敗", "失敗率"]} rows={(rankings?.failedCommands ?? []).map((row) => [row.target ? `${row.name} ${row.target}` : row.name, String(row.executions), String(row.failures), `${(row.failureRate * 100).toFixed(0)}%`])} /></Section>
      <Section title="書き直しファイル上位" actions={<Chip>数えた</Chip>}><RankingTable headers={["ファイル", "編集回数", "セッション数"]} rows={(rankings?.rewrittenFiles ?? []).map((row) => [row.path, String(row.editCount), String(row.sessionCount)])} /></Section>
      <Section title="決めごと"><FindingRows rows={filtered.filter((row) => decisionKinds.includes(row.kind))} onOpenDetail={onOpenDetail} onOpenRecord={onOpenRecord} /></Section>
      <Section title="ルール通信簿"><div style={{ display: "grid", gap: 12, gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))" }}>{rules ? <><RuleList title="巨大コンテキスト (300k超)" finding={rules.largeContext} onOpenDetail={onOpenDetail} /><RuleList title="compact 発生" finding={rules.compacted} onOpenDetail={onOpenDetail} /></> : <div style={noteStyle}>ルール通信簿を読み込み中です。</div>}</div></Section>
      {findings && (hasMore ?? rows.length < findings.total) ? <button type="button" onClick={onLoadMore} disabled={loading} style={{ ...subtleButtonStyle, alignSelf: "flex-start" }}>さらに読み込む</button> : null}
    </>}
  </div>;
});

function FindingSection({ title, rows, onOpenDetail, onOpenRecord, onCopyRule }: { title: string; rows: FindingsReport["rows"]; onOpenDetail: (kind: string, sessionId: string) => void; onOpenRecord: (date: number) => void; onCopyRule: (text: string) => void }) { return <Section title={title}><FindingRows rows={rows} onOpenDetail={onOpenDetail} onOpenRecord={onOpenRecord} onCopyRule={onCopyRule} /></Section>; }
function FindingRows({ rows, onOpenDetail, onOpenRecord, onCopyRule }: { rows: FindingsReport["rows"]; onOpenDetail: (kind: string, sessionId: string) => void; onOpenRecord: (date: number) => void; onCopyRule?: (text: string) => void }) { return rows.length === 0 ? <div style={noteStyle}>この分類の記録はまだありません (要約が進むと増えます)</div> : <div style={{ display: "flex", flexDirection: "column", gap: 7 }}>{rows.map((row, index) => <div key={`${row.sessionKind}:${row.sessionId}:${index}`} style={rowStyle}><button type="button" onClick={() => onOpenDetail(row.sessionKind, row.sessionId)} style={rowButtonStyle}><div style={{ display: "flex", gap: 6, alignItems: "center", flexWrap: "wrap" }}><Chip tone="accent">{KIND_LABELS[row.kind]}</Chip>{row.repeatCount >= 2 ? <Chip tone="warn">同じ罠 {row.repeatCount} 回目</Chip> : null}<span style={noteStyle}>{new Date(row.date).toLocaleDateString("ja-JP")} · {row.projectLabel ?? "—"}</span></div><div style={{ marginTop: 5, fontSize: "var(--cmux-font-size-sm)" }}>{row.text}</div></button>{row.kind === "gotcha" && row.repeatCount >= 2 && Number.isFinite(row.date) && row.date > 0 ? <button type="button" onClick={() => onOpenRecord(row.date)} style={{ ...subtleButtonStyle, marginTop: 8 }}>その日の記録へ</button> : null}{onCopyRule ? <button type="button" onClick={() => onCopyRule(row.text)} style={{ ...subtleButtonStyle, marginTop: 8 }}>ルール文をコピー</button> : null}</div>)}</div>; }
function RuleList({ title, finding, onOpenDetail }: { title: string; finding: RuleCheckFinding; onOpenDetail: (kind: string, sessionId: string) => void }) { return <div style={{ display: "flex", flexDirection: "column", gap: 6 }}><div style={{ fontWeight: 700 }}>{`${title}: ${finding.count} 件`}</div>{finding.count === 0 ? <div style={noteStyle}>該当するセッションがありません (期間を広げると増えることがあります)</div> : finding.sessions.map((session) => <button key={`${session.kind}:${session.sessionId}`} type="button" onClick={() => onOpenDetail(session.kind, session.sessionId)} style={rowStyle}>{session.title ?? session.sessionId} · {session.costUsd.toLocaleString("en-US", { style: "currency", currency: "USD" })}</button>)}</div>; }
function RankingTable({ headers, rows }: { headers: string[]; rows: string[][] }) { return <ScrollBox><table style={tableStyle}><thead><tr>{headers.map((header, index) => <th key={header} style={index === 0 ? thLeftStyle : thStyle}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${row[0]}:${index}`}>{row.map((value, cell) => <td key={cell} style={cell === 0 ? tdLeftStyle : tdStyle} title={value}>{value}</td>)}</tr>)}</tbody></table></ScrollBox>; }

LearningView.displayName = "LearningView";
const searchStyle = { height: 28, minWidth: 180, border: "1px solid var(--cmux-border)", borderRadius: 5, background: "var(--cmux-hover)", color: "var(--cmux-text)", padding: "0 8px", fontSize: "var(--cmux-font-size-xs)" };
const rowStyle = { textAlign: "left" as const, border: "1px solid var(--cmux-border-hairline)", borderRadius: 6, background: "var(--cmux-hover)", color: "var(--cmux-text)", padding: "8px 10px" };
const rowButtonStyle = { width: "100%", textAlign: "left" as const, border: 0, background: "transparent", color: "inherit", padding: 0, cursor: "pointer" };
