export const skillsStrings = {
  title: "スキル",
  shelf: "棚",
  shelves: "棚を選ぶ",
  all: "すべて",
  frequent: "よく使う",
  new: "新しい",
  recent: "最近変わった",
  hidden: "隠したもの",
  bundled: "mycmux 同梱",
  plugin: "プラグイン",
  builtin: "最初から入っている",
  command: "コマンド",
  other: "そのほか",
  search: "スキルを探す",
  searchPlaceholder: "名前・説明・本文から探す",
  searchResults: "探した結果",
  refresh: "読み直す",
  close: "閉じる",
  dismiss: "知らせを閉じる",
  list: "スキルの一覧",
  details: "スキルの詳細",
  detailTabs: "詳細の面",
  filterAgent: "使う相手で絞る",
  sort: "並べ替え",
  sortUsage: "よく使う順",
  sortName: "名前順",
  sortRecent: "最近変わった順",
  sortSize: "大きい順",
  loading: "読み込んでいます",
  noResults: "当てはまるスキルはありません",
  selectSkill: "一覧からスキルを選ぶと、中身がここに出ます",
  noWorkspace: "今のワークスペースにタブを開いてから始めてください",
  noDocument: "本文のファイルはありません。エージェントで呼び出して使います",
  agentUnavailable: "この相手では呼び出せません",
  claudeUsage: "Claude の記録",
  codexUsage: "Codex が SKILL.md を読んだ回",
  noRecord: "記録なし",
  usageNote: "よく使うは Claude と Codex の合計。Codex は SKILL.md を読んだ回",
  startClaude: "Claude で始める",
  startCodex: "Codex で始める",
  share: "共有",
  folder: "フォルダ",
  expand: "広げる",
  collapse: "一覧に戻る",
  editor: "エディタで開く",
  repair: "AI に直してもらう",
  duplicateTag: "Codex 重複",
  wrapperTag: "入口あり",
  duplicateWarning: "Codex に同じ名前が 2 つあります。$名前 が効かないおそれがあります",
  curationHelp: "表示の出どころ。推定は名前と説明の語から分類しています",
  copyCall: "呼び方をコピー",
  copied: "呼び方をコピーしました",
  unsorted: "未分類",
  back: "戻る",
  shareTitle: "共有するファイルを選ぶ",
  shareNote: "仕組みは含め、記録・出力・鍵・キャッシュは外します。必要なものは選び直せます",
  shareLimits: "上限 50 MB / 5,000 ファイル",
  saving: "保存しています",
  saveZip: "ZIP を保存",
  bodyMatch: "本文で当たった所",
  description: "説明",
  triggers: "きっかけの語",
  exclusions: "対象外",
  tools: "使う道具",
  size: "大きさ・更新",
  searchInside: "本文の中を探す",
  toc: "目次",
  fileTree: "ファイルの木",
  selectFile: "表示するファイルを選んでください",
  openExternally: "外のアプリで開く",
  placesTitle: "置き場所の関係",
  readOnly: "見るだけ",
  target: "行き先",
  exists: "あり",
  missing: "なし",
  sameDescription: "入口の説明は本体と同じ",
  differentDescription: "入口の説明は本体と違います",
  sameContent: "本体と中身が同じ写し",
  differentContent: "本体と中身が違う写し",
  diffLeft: "比べる左",
  diffRight: "比べる右",
  showDiff: "行ごとの差分を見る",
  diff: "行ごとの差分",
  diffTooLarge: "大きすぎるため、エディタで比べてください",
  noPlaces: "置き場所の記録がありません",
  bundledReadOnly: "mycmux 同梱の導入状態です。導入と更新は設定の AI の欄から行います",
  fileKinds: { md: "Markdown", text: "テキスト", image: "画像", pdf: "PDF", binary: "外部ファイル", folder: "フォルダ" } as Record<string, string>,
  groups: {"name":"名前と説明","trigger":"きっかけの語","body":"本文"} as Record<string, string>,
  tabs: {"content":"中身","folder":"フォルダ","places":"置き場所"} as Record<string, string>,
  kinds: {"own":"自作","plugin":"プラグイン","builtin":"最初から入っている","command":"コマンド"} as Record<string, string>,
  curations: {"guess":"推定","auto":"AI の案","shipped":"配る定義","skill":"SKILL.md の定義","manual":"個人の定義"} as Record<string, string>,
  relations: {"source":"本体","wrapper":"入口","copy":"写し","junction":"junction（生）","brokenJunction":"junction（壊）","independent":"独自"} as Record<string, string>,
  reasons: {"backup":"控え","record":"記録","output":"作った結果","config":"設定","data":"データ","large":"大きすぎる","cache":"キャッシュ（共有できません）","private":"鍵らしい名前（中身と共有を禁止）","link":"リンク（共有できません）"} as Record<string, string>,

  date: (value: number | null | undefined) => value ? new Date(value).toLocaleDateString("ja-JP") : "使った記録なし",
  catalogStatus: (count: number, date: string | undefined, busy: boolean) => `${count} 本 · ${busy ? "読み直しています" : date ? new Date(date).toLocaleTimeString("ja-JP") + " 更新" : "前回の結果を確認しています"}`,
  error: (message: string) => `操作できませんでした: ${message}`,
  cacheError: (message: string) => `前回の結果を読めませんでした。読み直しています: ${message}`,
  repairPrompt: (path: string) => `${path} のスキルを直したい。まず中身を読み、何を直すか聞いてください`,
  saved: (path: string) => `ZIP を保存しました: ${path}`,
  documentSize: (lines: number, size: string) => `${lines} 行 · ${size}`,
  folderSize: (files: number, size: string) => `${files} ファイル · ${size}`,
  fileCount: (count: number | null) => count === null ? "ファイル数は未確認" : `${count} ファイル`,
  shareSize: (files: number, size: string) => `共有するもの: ${files} ファイル · ${size}`,
  implicit: (value: boolean | null) => value === null ? "自動起動: 指定なし" : value ? "自動起動: 許可" : "自動起動: 不許可",
  bundledState: (state: string) => (({ missing: "未導入", installed: "導入済み", current: "最新", modified: "手元で変更あり", outdated: "更新あり" } as Record<string, string>)[state] ?? state),
};
