import { createElement } from "react";
import type { LucideIcon } from "lucide-react";
import { Activity, AlarmClock, Archive, ArrowLeftRight, AtSign, BadgeCheck, Binoculars, Book, BookOpen, Braces, Brain, Briefcase, BriefcaseMedical, Calendar, CalendarClock, ChartColumn, ChartLine, ChartPie, ChartScatter, CircleDot, CircleHelp, Clipboard, ClipboardPen, Command, Compass, CopyPlus, Crosshair, Database, Download, Drama, Eye, FileCog, FileLock, FilePlus, FileSearch, FileText, Files, Film, Flag, Flame, Folder, Gauge, GitBranch, GitMerge, GitPullRequest, Glasses, Globe, GraduationCap, Grid3X3, Hammer, Hand, HardDrive, Hash, Heart, Highlighter, Image, Inbox, JapaneseYen, Keyboard, Layers, Lightbulb, ListChecks, Mail, MapPin, MessageCircle, MessageSquareCheck, MessagesSquare, Monitor, Mouse, MousePointer, Music, Package, Paintbrush, Palette, PanelsTopLeft, PawPrint, PencilLine, Plane, Play, Printer, Puzzle, Rabbit, RefreshCw, Ruler, ScanText, Scissors, Search, Send, Settings, Shield, ShieldCheck, SlidersHorizontal, SlidersVertical, Smartphone, Stethoscope, Sun, Sunrise, Table, Terminal, TriangleAlert, Type, Upload, UserCheck, Users, WandSparkles, Zap } from "lucide-react";

/** SF Symbols identifiers are the shared canonical keys. */
export const symbolMap: Record<string, LucideIcon> = {
  "airplane": Plane,
  "airplane.departure": Plane,
  "alarm": AlarmClock,
  "angle": Ruler,
  "archivebox": Archive,
  "archivebox.circle": Archive,
  "arrow.clockwise.circle": RefreshCw,
  "arrow.down.app": Download,
  "arrow.left.arrow.right": ArrowLeftRight,
  "arrow.triangle.branch": GitBranch,
  "arrow.triangle.merge": GitMerge,
  "arrow.triangle.pull": GitPullRequest,
  "arrow.up.doc": Upload,
  "at": AtSign,
  "binoculars": Binoculars,
  "bolt.horizontal": Zap,
  "book": BookOpen,
  "book.closed": Book,
  "books.vertical": BookOpen,
  "brain.head.profile": Brain,
  "briefcase": Briefcase,
  "bubble.left.and.bubble.right": MessagesSquare,
  "calendar.badge.clock": CalendarClock,
  "calendar.day.timeline.left": Calendar,
  "character.textbox": Type,
  "chart.bar": ChartColumn,
  "chart.bar.doc.horizontal": ChartColumn,
  "chart.bar.xaxis": ChartColumn,
  "chart.dots.scatter": ChartScatter,
  "chart.line.uptrend.xyaxis": ChartLine,
  "chart.pie": ChartPie,
  "chart.xyaxis.line": ChartLine,
  "checklist": ListChecks,
  "checkmark.bubble": MessageSquareCheck,
  "checkmark.rectangle": ListChecks,
  "checkmark.rectangle.stack": ListChecks,
  "checkmark.seal": BadgeCheck,
  "checkmark.shield": ShieldCheck,
  "clock.arrow.circlepath": RefreshCw,
  "command": Command,
  "compass.drawing": Ruler,
  "computermouse": Mouse,
  "cross.case": BriefcaseMedical,
  "curlybraces": Braces,
  "curlybraces.square": Braces,
  "cursorarrow": MousePointer,
  "cylinder.split.1x2": Database,
  "desktopcomputer": Monitor,
  "display": Monitor,
  "doc.badge.gearshape": FileCog,
  "doc.badge.plus": FilePlus,
  "doc.on.clipboard": Clipboard,
  "doc.on.doc": Files,
  "doc.plaintext": FileText,
  "doc.plaintext.fill": FileText,
  "doc.richtext": FileText,
  "doc.text": FileText,
  "doc.text.fill": FileText,
  "doc.text.magnifyingglass": FileSearch,
  "doc.viewfinder": ScanText,
  "envelope": Mail,
  "envelope.arrow.triangle.branch": GitBranch,
  "envelope.badge": Mail,
  "exclamationmark.triangle": TriangleAlert,
  "externaldrive": HardDrive,
  "eye": Eye,
  "eyeglasses": Glasses,
  "film": Film,
  "film.stack": Film,
  "flag.checkered": Flag,
  "flame": Flame,
  "flowchart": GitBranch,
  "function": Braces,
  "gearshape": Settings,
  "globe": Globe,
  "graduationcap": GraduationCap,
  "hammer": Hammer,
  "hammer.circle": Hammer,
  "hand.raised": Hand,
  "hare": Rabbit,
  "heart": Heart,
  "heart.text.square": Heart,
  "highlighter": Highlighter,
  "iphone": Smartphone,
  "keyboard": Keyboard,
  "lightbulb": Lightbulb,
  "list.bullet.clipboard": Clipboard,
  "lock.doc": FileLock,
  "lock.shield": Shield,
  "macmini": HardDrive,
  "macwindow": Monitor,
  "macwindow.on.rectangle": Monitor,
  "magnifyingglass": Search,
  "magnifyingglass.circle": Search,
  "mappin.and.ellipse": MapPin,
  "music.note": Music,
  "number.square": Hash,
  "paintbrush": Paintbrush,
  "paintpalette": Palette,
  "paperplane": Send,
  "pawprint": PawPrint,
  "pc": Monitor,
  "pencil.and.list.clipboard": ClipboardPen,
  "pencil.line": PencilLine,
  "person.2": Users,
  "person.3": Users,
  "person.bubble": MessageCircle,
  "person.crop.circle.badge.checkmark": UserCheck,
  "person.crop.circle.badge.questionmark": CircleHelp,
  "photo.artframe": Image,
  "photo.on.rectangle.angled": Image,
  "play": Play,
  "play.circle": Play,
  "play.rectangle": Play,
  "play.rectangle.on.rectangle": Play,
  "play.tv": Play,
  "plus.rectangle.on.rectangle": CopyPlus,
  "plus.square.on.square": CopyPlus,
  "printer": Printer,
  "puzzlepiece": Puzzle,
  "puzzlepiece.extension": Puzzle,
  "questionmark.bubble": CircleHelp,
  "questionmark.folder": Folder,
  "record.circle": CircleDot,
  "rectangle.3.group": PanelsTopLeft,
  "rectangle.on.rectangle": PanelsTopLeft,
  "rectangle.on.rectangle.angled": PanelsTopLeft,
  "rectangle.split.3x1": PanelsTopLeft,
  "rectangle.stack": Layers,
  "repeat": RefreshCw,
  "rosette": BadgeCheck,
  "ruler": Ruler,
  "safari": Compass,
  "scissors": Scissors,
  "scope": Crosshair,
  "shippingbox": Package,
  "shippingbox.circle": Package,
  "signature": PencilLine,
  "slider.horizontal.3": SlidersHorizontal,
  "slider.vertical.3": SlidersVertical,
  "speedometer": Gauge,
  "square.and.arrow.down": Download,
  "square.and.arrow.down.on.square": Download,
  "square.and.pencil": PencilLine,
  "square.grid.3x3": Grid3X3,
  "square.stack.3d.up": Layers,
  "squareshape.split.3x3": Grid3X3,
  "stethoscope": Stethoscope,
  "sum": Braces,
  "sun.horizon": Sunrise,
  "sun.max": Sun,
  "sunrise": Sunrise,
  "tablecells": Table,
  "tablecells.badge.ellipsis": Table,
  "tablecells.fill": Table,
  "target": Crosshair,
  "terminal": Terminal,
  "text.badge.checkmark": ListChecks,
  "text.book.closed": BookOpen,
  "text.bubble": MessageCircle,
  "text.magnifyingglass": Search,
  "textformat": Type,
  "theatermasks": Drama,
  "tray.2": Inbox,
  "tray.and.arrow.down": Download,
  "tray.and.arrow.down.fill": Download,
  "tray.full": Inbox,
  "wand.and.rays": WandSparkles,
  "wand.and.stars": WandSparkles,
  "waveform.path.ecg": Activity,
  "yensign": JapaneseYen,
  "yensign.circle": JapaneseYen,
};
export function SkillSymbol({ symbol, fallback, size = 18 }: { symbol: string | null; fallback?: string | null; size?: number }) {
  const Icon = symbolMap[symbol ?? ""] ?? symbolMap[fallback ?? ""] ?? Folder;
  return createElement(Icon, { size, strokeWidth: 1.8, "aria-hidden": true });
}


/** Keep category accents on the application's existing theme tokens. */
export function categoryTone(category: string): string {
  const tones: Record<string, string> = {
    edu: "var(--cmux-status-stall)", gate: "var(--cmux-usage-ok)",
    desk: "var(--cmux-usage-warn)", doc: "var(--cmux-accent-text)",
    viz: "var(--cmux-red)", scout: "var(--cmux-status-stall)",
    money: "var(--cmux-usage-warn)", daily: "var(--cmux-accent-text)",
    dev: "var(--cmux-usage-ok)", code: "var(--cmux-text-secondary)",
    operate: "var(--cmux-usage-warn)", misc: "var(--cmux-usage-ok)",
  };
  return tones[category] ?? "var(--cmux-text-secondary)";
}
