<#
.SYNOPSIS
  Publishes the wallpaper pack that the app downloads from.

.DESCRIPTION
  Stages the 59 originals under the distribution names the manifest declares
  (<id>.webp), re-checks every sha256 against the manifest so a corrupted
  working copy cannot be published, and uploads them to a release on the public
  mirror. The app builds its URLs as
  <PACK_RELEASE_BASE>/<packTag>/<filename>, so the tag in
  scripts/wallpapers/sources.json is what decides which release is live.

  Dry run by default. Nothing is created or uploaded without -Execute, because
  publishing is an external, public action.

.EXAMPLE
  powershell -File scripts/wallpapers/publish_pack.ps1
  powershell -File scripts/wallpapers/publish_pack.ps1 -Execute
#>
[CmdletBinding()]
param(
  [string]$Repo = 'miyafcos/mycmux-team',
  # Defaults to the packTag in the manifest; pass this only to publish a new pack.
  [string]$Tag,
  [switch]$Execute
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$manifestPath = Join-Path $repoRoot 'src/assets/wallpaper-manifest.json'
$sourcesPath = Join-Path $repoRoot 'scripts/wallpapers/sources.json'

if (-not (Test-Path $manifestPath)) { throw "Manifest not found: $manifestPath" }
if (-not (Test-Path $sourcesPath)) { throw "Sources not found: $sourcesPath" }

$manifest = Get-Content -LiteralPath $manifestPath -Raw -Encoding UTF8 | ConvertFrom-Json
$sources = Get-Content -LiteralPath $sourcesPath -Raw -Encoding UTF8 | ConvertFrom-Json
if (-not $Tag) { $Tag = $manifest.packTag }

$sourceById = @{}
foreach ($entry in $sources.wallpapers) { $sourceById[$entry.id] = $entry.source }

$staging = Join-Path ([System.IO.Path]::GetTempPath()) ("mycmux-wallpaper-pack-" + $Tag)
if (Test-Path $staging) { Remove-Item -LiteralPath $staging -Recurse -Force -Confirm:$false }
New-Item -ItemType Directory -Path $staging | Out-Null

$staged = New-Object System.Collections.Generic.List[string]
$totalBytes = 0L
foreach ($entry in $manifest.wallpapers) {
  $relative = $sourceById[$entry.id]
  if (-not $relative) { throw "No source recorded for wallpaper id '$($entry.id)'" }
  $source = Join-Path $repoRoot $relative
  if (-not (Test-Path -LiteralPath $source)) { throw "Missing original: $relative" }

  $digest = (Get-FileHash -LiteralPath $source -Algorithm SHA256).Hash.ToLowerInvariant()
  if ($digest -ne $entry.sha256) {
    throw "sha256 mismatch for $($entry.id): working copy $digest, manifest $($entry.sha256). Re-run build_manifest.py or restore the original."
  }
  $length = (Get-Item -LiteralPath $source).Length
  if ($length -ne $entry.bytes) {
    throw "size mismatch for $($entry.id): working copy $length, manifest $($entry.bytes)"
  }

  $target = Join-Path $staging $entry.filename
  Copy-Item -LiteralPath $source -Destination $target
  $staged.Add($target) | Out-Null
  $totalBytes += $length
}

Write-Host ("Staged {0} wallpapers ({1:N1} MiB) in {2}" -f $staged.Count, ($totalBytes / 1MB), $staging)
Write-Host ("Target: {0}  tag: {1}" -f $Repo, $Tag)

if (-not $Execute) {
  Write-Host 'Dry run. Re-run with -Execute to create the release and upload.'
  exit 0
}

# No stderr redirection: PS 5.1 turns a native command's stderr into
# NativeCommandError records, and gh writes "release not found" there on the
# path we are deliberately testing for.
& gh release view $Tag --repo $Repo | Out-Null
if ($LASTEXITCODE -ne 0) {
  & gh release create $Tag --repo $Repo --title "mycmux wallpapers ($Tag)" `
    --notes 'Full-resolution wallpapers downloaded on demand by mycmux. Generated by scripts/wallpapers/publish_pack.ps1.'
  if ($LASTEXITCODE -ne 0) { throw 'gh release create failed' }
}

& gh release upload $Tag --repo $Repo --clobber @($staged)
if ($LASTEXITCODE -ne 0) { throw 'gh release upload failed' }

Write-Host ("Uploaded {0} files to {1} {2}" -f $staged.Count, $Repo, $Tag)
