use serde_json::Value;

pub fn trim_preview(value: &str, max_chars: usize) -> String {
    let mut out = value
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .trim()
        .to_string();
    if out.chars().count() > max_chars {
        out = out.chars().take(max_chars.saturating_sub(3)).collect();
        out.push_str("...");
    }
    out
}

pub fn trim_transcript(value: &str, max_chars: Option<usize>) -> String {
    let mut out = value
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n")
        .trim()
        .to_string();
    if let Some(max_chars) = max_chars {
        if out.chars().count() > max_chars {
            out = out.chars().take(max_chars.saturating_sub(13)).collect();
            out.push_str("\n[truncated]");
        }
    }
    out
}

pub fn extract_text_from_value(value: &Value) -> Option<String> {
    if let Some(text) = value.as_str() {
        return Some(text.to_string());
    }
    if let Some(array) = value.as_array() {
        let parts = array
            .iter()
            .filter_map(extract_text_from_value)
            .collect::<Vec<_>>();
        if parts.is_empty() {
            return None;
        }
        return Some(parts.join("\n"));
    }
    let object = value.as_object()?;
    for key in ["text", "content", "message", "body", "summary"] {
        if let Some(child) = object.get(key).and_then(extract_text_from_value) {
            return Some(child);
        }
    }
    None
}

fn extract_visible_text_parts(value: &Value) -> Vec<String> {
    if let Some(text) = value.as_str() {
        return vec![text.to_string()];
    }
    if let Some(array) = value.as_array() {
        return array.iter().flat_map(extract_visible_text_parts).collect();
    }
    let Some(object) = value.as_object() else {
        return Vec::new();
    };

    match object.get("type").and_then(Value::as_str) {
        Some("text") | Some("input_text") | Some("output_text") => object
            .get("text")
            .and_then(Value::as_str)
            .map(|text| vec![text.to_string()])
            .unwrap_or_default(),
        Some("tool_result") | Some("tool_use") | Some("thinking") | Some("redacted_thinking") => {
            Vec::new()
        }
        Some(_) => object
            .get("text")
            .or_else(|| object.get("content"))
            .map(extract_visible_text_parts)
            .unwrap_or_default(),
        None => object
            .get("text")
            .or_else(|| object.get("content"))
            .or_else(|| object.get("message"))
            .or_else(|| object.get("body"))
            .or_else(|| object.get("summary"))
            .map(extract_visible_text_parts)
            .unwrap_or_default(),
    }
}

fn strip_xml_blocks(text: &str, tag: &str) -> String {
    let start = format!("<{tag}>");
    let end = format!("</{tag}>");
    let mut rest = text;
    let mut out = String::new();

    while let Some(start_index) = rest.find(&start) {
        out.push_str(&rest[..start_index]);
        let after_start = &rest[start_index + start.len()..];
        let Some(end_index) = after_start.find(&end) else {
            rest = "";
            break;
        };
        rest = &after_start[end_index + end.len()..];
    }
    out.push_str(rest);
    out
}

fn strip_claude_injected_context(text: &str) -> String {
    let text = strip_xml_blocks(text, "system-reminder");
    trim_transcript(&text, None)
}

fn is_claude_context_noise(text: &str) -> bool {
    let trimmed = text.trim_start();
    trimmed.is_empty()
        || trimmed.starts_with("<system-reminder>")
        || trimmed.starts_with("# AGENTS.md instructions")
        || trimmed.starts_with("<!-- AUTO-GENERATED by ~/.claude/scripts/sync-agents-md.sh")
}

pub fn extract_codex_visible_text(value: &Value) -> Option<String> {
    let kind = value.get("type").and_then(Value::as_str)?;
    if kind != "response_item" {
        return None;
    }

    let payload = value.get("payload").unwrap_or(value);
    let role = payload.get("role").and_then(Value::as_str)?;
    if !matches!(role, "user" | "assistant") {
        return None;
    }
    let text = extract_text_from_value(payload)?;
    let text = trim_preview(&text, 360);
    if text.is_empty() || is_codex_context_noise(value, payload, &text) {
        return None;
    }
    Some(text)
}

fn is_codex_context_noise(root: &Value, payload: &Value, text: &str) -> bool {
    if root.get("token_count").is_some()
        || root.get("rate_limits").is_some()
        || payload.get("base_instructions").is_some()
        || payload.get("token_count").is_some()
        || payload.get("rate_limits").is_some()
    {
        return true;
    }

    let trimmed = text.trim_start();
    trimmed.starts_with("<permissions instructions>")
        || trimmed.starts_with("<environment_context>")
        || trimmed.starts_with("<collaboration_mode>")
        || trimmed.starts_with("<apps_instructions>")
        || trimmed.starts_with("<skills_instructions>")
        || trimmed.starts_with("# AGENTS.md instructions")
}

pub fn extract_claude_visible_text(value: &Value) -> Option<(String, String)> {
    extract_claude_text(value, true)
}

pub fn extract_claude_handoff_text(value: &Value) -> Option<(String, String)> {
    extract_claude_text(value, false)
}

fn extract_claude_text(value: &Value, preview: bool) -> Option<(String, String)> {
    let kind = value.get("type").and_then(Value::as_str)?;
    if !matches!(kind, "user" | "assistant") {
        return None;
    }
    let message = value.get("message")?;
    let role = message
        .get("role")
        .and_then(Value::as_str)
        .unwrap_or(kind)
        .to_string();
    let parts = extract_visible_text_parts(message.get("content")?);
    let text = strip_claude_injected_context(&parts.join("\n"));
    if is_claude_context_noise(&text) {
        return None;
    }
    let text = if preview {
        trim_preview(&text, 1200)
    } else {
        trim_transcript(&text, None)
    };
    Some((role, text))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn claude_extraction_skips_tool_results() {
        let value = json!({
            "type": "user",
            "message": {
                "role": "user",
                "content": [
                    { "type": "tool_result", "content": "MEMORY.md full text" },
                    { "type": "text", "text": "Real user message" }
                ]
            }
        });

        let (_, text) = extract_claude_handoff_text(&value).unwrap();
        assert_eq!(text, "Real user message");
    }

    #[test]
    fn claude_extraction_preserves_multiline_handoff_text() {
        let value = json!({
            "type": "user",
            "message": {
                "role": "user",
                "content": [{ "type": "text", "text": "```rust\nfn main() {\n    println!(\"hi\");\n}\n```" }]
            }
        });

        let (_, text) = extract_claude_handoff_text(&value).unwrap();
        assert!(text.contains("fn main() {\n    println!"));
    }

    #[test]
    fn claude_extraction_strips_inline_system_reminders() {
        let value = json!({
            "type": "user",
            "message": {
                "role": "user",
                "content": [{
                    "type": "text",
                    "text": "Keep this\n<system-reminder>internal note</system-reminder>\nAnd this"
                }]
            }
        });

        let (_, text) = extract_claude_handoff_text(&value).unwrap();
        assert_eq!(text, "Keep this\n\nAnd this");
    }

    #[test]
    fn codex_noise_filter_does_not_drop_plain_token_words() {
        let value = json!({
            "type": "response_item",
            "payload": {
                "role": "user",
                "content": [{ "type": "input_text", "text": "Please explain token_count in this log." }]
            }
        });

        assert!(extract_codex_visible_text(&value).is_some());
    }
}
