// ダッシュボード (全ワークスペース×全ペインの一覧) の文言。
// 用語は「ワークスペース > タブ > ペイン」(2026-08-11 確定)。
// 表示方針: 一覧面はアイコン+数字+最短ラベル、のぞき窓だけ言葉を許す (モック第5便)。
export const dashboardStrings = {
  buttonTitle: "ダッシュボード",
  panelAriaLabel: "ダッシュボード — 全ペイン一覧",
  groupWaiting: "要対応",
  groupWaitingSub: "返事待ち",
  groupStalled: "止まってるかも",
  groupStalledSub: "無反応・未送信・落ちた",
  groupWorking: "作業中",
  groupDone: "完了",
  sortByWorkspace: "ワークスペース順",
  sortByAttention: "要対応順",
  visibleCount: "表示中",
  backgroundCount: "裏で稼働",
  backgroundBadge: "裏",
  unobservedBadge: "観測外",
  liveUpdating: "自動更新中",
  peekButton: "のぞく",
  jumpButton: "移動 ▸",
  jumpButtonTitle: "このペインへ移動",
  myInstructionLabel: "私の指示",
  agentAskingLabel: "エージェントの質問",
  clearDoneButton: (n: number): string => `完了 ${n}件を既読にする`,
  peekEscHint: "Esc で戻る",
  peekPrev: "← 前",
  peekNext: "次 →",
  emptyState: "表示できるペインがありません",
  countUnit: (n: number): string => `${n}件`,
  paneLocation: (tab: number | string, pane: number | string): string => `タブ${tab}·P${pane}`,
  // 停滞理由 (P5: 常時検知の3分類)
  stallNoOutput: "5分以上 出力なし",
  stallQueuedInput: "未送信の指示が残っている",
  stallPtyDead: "プロセスが終了している",
  stallSince: (min: number): string => `${min}分 無反応`,
  stallQueuedPreviewLabel: "未送信テキスト",
  // フルスクリーンビュー化 (2026-08-11) で追加
  viewAriaLabel: "ダッシュボード — 全ペイン俯瞰ビュー",
  groupIdle: "待機",
  sortByAgent: "エージェント別",
  searchPlaceholder: "検索 (ワークスペース・ラベル・cwd・ログ)",
  backToSession: "セッションへ戻る",
  urgentRibbonTitle: "最優先",
  filterTitle: "フィルタ",
  filterAttentionOnly: "要対応のみ",
  filterStalledOnly: "停滞のみ",
  filterBackgroundOnly: "裏で稼働のみ",
  filterUnobservedOnly: "観測外のみ",
  agentFilterTitle: "エージェント",
  allWorkspaces: "全て",
  keyboardHint: "j/k 選択 · Enter 移動 · Tab 次の要対応 · / 検索 · Esc 戻る",
  markReadButton: "完了を既読",
  totalSummary: (panes: number, ws: number): string => `全${panes}ペイン / ${ws}ワークスペース`,
  filteredSummary: (n: number, m: number): string => `絞り込み ${n} / 全 ${m}`,
  detailEmpty: "カードを選ぶと詳細が出ます",
  tailTitle: "画面の末尾 40行",
} as const;
