import type { ThemeDefinition, ThemeGroup } from "../../types";

export const DEFAULT_THEME_ID = "mayonaka";

export const THEME_GROUPS: Array<{ id: ThemeGroup; label: string; hint: string }> = [
  { id: "calm-dark", label: "静かな暗色", hint: "長時間作業向け" },
  { id: "vivid-dark", label: "個性の強い暗色", hint: "色の違いが明確" },
  { id: "light", label: "明るい配色", hint: "昼間や資料作業向け" },
];

export const THEMES: ThemeDefinition[] = [
  {
    id: "mayonaka",
    name: "真夜中",
    group: "calm-dark",
    description: "純黒・やわらかい差し色",
    terminal: {
      background: "#07090d",
      foreground: "#edf2f7",
      cursor: "#9bd0ff",
      selectionBackground: "#1d2735",
      black: "#111827",
      red: "#fb7185",
      green: "#4ade80",
      yellow: "#fbbf24",
      blue: "#60a5fa",
      magenta: "#c084fc",
      cyan: "#67e8f9",
      white: "#cbd5e1",
      brightBlack: "#334155",
      brightRed: "#fda4af",
      brightGreen: "#86efac",
      brightYellow: "#fcd34d",
      brightBlue: "#93c5fd",
      brightMagenta: "#d8b4fe",
      brightCyan: "#a5f3fc",
      brightWhite: "#f8fafc",
    },
    chrome: {
      background: "#020408",
      surface: "#07090d",
      border: "#172033",
      text: "#edf2f7",
      textMuted: "#64748b",
      accent: "#60a5fa",
    },
  },
  {
    id: "kyokuya",
    name: "極夜",
    group: "calm-dark",
    description: "寒色・北欧トーン",
    terminal: {
      background: "#2e3440",
      foreground: "#d8dee9",
      cursor: "#88c0d0",
      selectionBackground: "#434c5e",
      black: "#3b4252",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#81a1c1",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#e5e9f0",
      brightBlack: "#4c566a",
      brightRed: "#bf616a",
      brightGreen: "#a3be8c",
      brightYellow: "#ebcb8b",
      brightBlue: "#81a1c1",
      brightMagenta: "#b48ead",
      brightCyan: "#8fbcbb",
      brightWhite: "#eceff4",
    },
    chrome: {
      background: "#242933",
      surface: "#2e3440",
      border: "#4c566a",
      text: "#d8dee9",
      textMuted: "#6b7280",
      accent: "#88c0d0",
    },
  },
  {
    id: "yoi-ai",
    name: "宵藍",
    group: "calm-dark",
    description: "藍色・レトロ端末",
    terminal: {
      background: "#002b36",
      foreground: "#93a1a1",
      cursor: "#2aa198",
      selectionBackground: "#073642",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#586e75",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
    chrome: {
      background: "#00212b",
      surface: "#002b36",
      border: "#073642",
      text: "#93a1a1",
      textMuted: "#586e75",
      accent: "#2aa198",
    },
  },
  {
    id: "shinkai",
    name: "深海",
    group: "calm-dark",
    description: "深海・ティール",
    terminal: {
      background: "#07131c",
      foreground: "#cde7f4",
      cursor: "#32d4c7",
      selectionBackground: "#123346",
      black: "#06101a",
      red: "#ff7a8a",
      green: "#5ee6a8",
      yellow: "#f6c177",
      blue: "#56b6ff",
      magenta: "#b794f4",
      cyan: "#32d4c7",
      white: "#c7d6e2",
      brightBlack: "#214057",
      brightRed: "#ff99a4",
      brightGreen: "#86efc2",
      brightYellow: "#ffd38b",
      brightBlue: "#8fd3ff",
      brightMagenta: "#ccb8ff",
      brightCyan: "#74efe4",
      brightWhite: "#eef8ff",
    },
    chrome: {
      background: "#030a10",
      surface: "#07131c",
      border: "#123346",
      text: "#cde7f4",
      textMuted: "#527288",
      accent: "#32d4c7",
    },
  },
  {
    id: "chikurin",
    name: "竹林",
    group: "calm-dark",
    description: "森林・深緑",
    terminal: {
      background: "#121b16",
      foreground: "#d7e5d8",
      cursor: "#6cc08b",
      selectionBackground: "#223229",
      black: "#0f1713",
      red: "#ff8b94",
      green: "#6cc08b",
      yellow: "#d7c97a",
      blue: "#7db1ff",
      magenta: "#c59bff",
      cyan: "#56d3c2",
      white: "#d1dbd3",
      brightBlack: "#385141",
      brightRed: "#ffb0b7",
      brightGreen: "#94dfaa",
      brightYellow: "#eadc9d",
      brightBlue: "#a8cdff",
      brightMagenta: "#debcff",
      brightCyan: "#84eadc",
      brightWhite: "#f2f8f2",
    },
    chrome: {
      background: "#0a110d",
      surface: "#121b16",
      border: "#223229",
      text: "#d7e5d8",
      textMuted: "#5b7563",
      accent: "#6cc08b",
    },
  },
  {
    id: "seijaku",
    name: "静寂",
    group: "calm-dark",
    description: "無彩色・OLED",
    terminal: {
      background: "#000000",
      foreground: "#9ca3af",
      cursor: "#e5e7eb",
      selectionBackground: "#101317",
      black: "#0b0d10",
      red: "#8f5f66",
      green: "#6b8a78",
      yellow: "#96856a",
      blue: "#6d869c",
      magenta: "#88729b",
      cyan: "#6a9191",
      white: "#9ca3af",
      brightBlack: "#374151",
      brightRed: "#b67b85",
      brightGreen: "#8fb09a",
      brightYellow: "#b7a588",
      brightBlue: "#95adc4",
      brightMagenta: "#b49fc4",
      brightCyan: "#93bbbb",
      brightWhite: "#f3f4f6",
    },
    chrome: {
      background: "#000000",
      surface: "#090b0f",
      border: "#171b21",
      text: "#d1d5db",
      textMuted: "#4b5563",
      accent: "#e5e7eb",
    },
  },
  {
    id: "yogiri",
    name: "夜霧",
    group: "vivid-dark",
    description: "ネオン紫・シアン",
    terminal: {
      background: "#1e1733",
      foreground: "#f8f4ff",
      cursor: "#ff74d4",
      selectionBackground: "#39235d",
      black: "#1a1230",
      red: "#ff6b8a",
      green: "#8effa0",
      yellow: "#ffe66d",
      blue: "#7aa2ff",
      magenta: "#c792ff",
      cyan: "#5cf2ff",
      white: "#efe7ff",
      brightBlack: "#5b4c80",
      brightRed: "#ff95ac",
      brightGreen: "#b4ffc0",
      brightYellow: "#fff0a0",
      brightBlue: "#adc6ff",
      brightMagenta: "#e0b7ff",
      brightCyan: "#a7fbff",
      brightWhite: "#ffffff",
    },
    chrome: {
      background: "#140d24",
      surface: "#1e1733",
      border: "#39235d",
      text: "#f8f4ff",
      textMuted: "#8c7bb5",
      accent: "#c792ff",
    },
  },
  {
    id: "ginga",
    name: "銀河",
    group: "vivid-dark",
    description: "宇宙紺・マゼンタ",
    terminal: {
      background: "#0a1020",
      foreground: "#f5f7ff",
      cursor: "#ff8abf",
      selectionBackground: "#1c2745",
      black: "#060b18",
      red: "#ff708d",
      green: "#89e089",
      yellow: "#ffd166",
      blue: "#82aaff",
      magenta: "#ff8abf",
      cyan: "#6be8ff",
      white: "#dbe3ff",
      brightBlack: "#2a3759",
      brightRed: "#ff9eb3",
      brightGreen: "#a9efaa",
      brightYellow: "#ffe29c",
      brightBlue: "#acc3ff",
      brightMagenta: "#ffb3d2",
      brightCyan: "#9df1ff",
      brightWhite: "#ffffff",
    },
    chrome: {
      background: "#050914",
      surface: "#0a1020",
      border: "#1c2745",
      text: "#f5f7ff",
      textMuted: "#61719b",
      accent: "#ff8abf",
    },
  },
  {
    id: "sango",
    name: "珊瑚",
    group: "vivid-dark",
    description: "珊瑚・プラム",
    terminal: {
      background: "#2b1824",
      foreground: "#fff3f7",
      cursor: "#ff7f91",
      selectionBackground: "#4a2636",
      black: "#24131d",
      red: "#ff7f91",
      green: "#8de5b6",
      yellow: "#ffd37a",
      blue: "#8fd8ff",
      magenta: "#ff9de1",
      cyan: "#60e1d8",
      white: "#f2dce5",
      brightBlack: "#5f3b4e",
      brightRed: "#ff9eb0",
      brightGreen: "#b2f0cb",
      brightYellow: "#ffe4aa",
      brightBlue: "#b8e8ff",
      brightMagenta: "#ffbfec",
      brightCyan: "#9cf3eb",
      brightWhite: "#ffffff",
    },
    chrome: {
      background: "#1d0f17",
      surface: "#2b1824",
      border: "#4a2636",
      text: "#fff3f7",
      textMuted: "#946377",
      accent: "#ff7f91",
    },
  },
  {
    id: "raimei",
    name: "雷鳴",
    group: "vivid-dark",
    description: "雷光・イエロー",
    terminal: {
      background: "#17191d",
      foreground: "#f8fafc",
      cursor: "#f8e45c",
      selectionBackground: "#2d333b",
      black: "#111318",
      red: "#ff6b6b",
      green: "#7ee787",
      yellow: "#f8e45c",
      blue: "#6cb6ff",
      magenta: "#d2a8ff",
      cyan: "#7df9ff",
      white: "#d0d7de",
      brightBlack: "#4b5563",
      brightRed: "#ff9b9b",
      brightGreen: "#a3f0ad",
      brightYellow: "#fff28b",
      brightBlue: "#9ecbff",
      brightMagenta: "#e4c1ff",
      brightCyan: "#adffff",
      brightWhite: "#ffffff",
    },
    chrome: {
      background: "#0c0e12",
      surface: "#17191d",
      border: "#2d333b",
      text: "#f8fafc",
      textMuted: "#6b7280",
      accent: "#f8e45c",
    },
  },
  {
    id: "yougan",
    name: "溶岩",
    group: "vivid-dark",
    description: "溶岩・朱赤",
    terminal: {
      background: "#120909",
      foreground: "#ffe6df",
      cursor: "#ff6b57",
      selectionBackground: "#351515",
      black: "#170d0d",
      red: "#ff6b57",
      green: "#8dd694",
      yellow: "#ffb347",
      blue: "#88b6ff",
      magenta: "#ff94c2",
      cyan: "#57d6c2",
      white: "#e6c5be",
      brightBlack: "#5a2b2b",
      brightRed: "#ff9a8b",
      brightGreen: "#b2ebba",
      brightYellow: "#ffd28b",
      brightBlue: "#b8d1ff",
      brightMagenta: "#ffb7d7",
      brightCyan: "#91f0e1",
      brightWhite: "#fff7f5",
    },
    chrome: {
      background: "#090404",
      surface: "#120909",
      border: "#351515",
      text: "#ffe6df",
      textMuted: "#946160",
      accent: "#ff6b57",
    },
  },
  {
    id: "kogane",
    name: "黄金",
    group: "vivid-dark",
    description: "黒金・ラグジュアリー",
    terminal: {
      background: "#15120a",
      foreground: "#f7f1dc",
      cursor: "#d8b44a",
      selectionBackground: "#302718",
      black: "#0f0c06",
      red: "#f38b70",
      green: "#99c27a",
      yellow: "#d8b44a",
      blue: "#7fb4ff",
      magenta: "#caa8ff",
      cyan: "#7ad8d0",
      white: "#d8ceb2",
      brightBlack: "#584b32",
      brightRed: "#ffb29c",
      brightGreen: "#b8d9a0",
      brightYellow: "#f0d47b",
      brightBlue: "#aacdff",
      brightMagenta: "#dec8ff",
      brightCyan: "#a6ece4",
      brightWhite: "#fffaf0",
    },
    chrome: {
      background: "#0a0805",
      surface: "#15120a",
      border: "#302718",
      text: "#f7f1dc",
      textMuted: "#8d7c58",
      accent: "#d8b44a",
    },
  },
  {
    id: "asanagi",
    name: "朝凪",
    group: "light",
    description: "ニュートラル青灰",
    terminal: {
      background: "#f4f7fb",
      foreground: "#223042",
      cursor: "#2f6fed",
      selectionBackground: "#d8e7ff",
      black: "#dfe7f1",
      red: "#c4585d",
      green: "#3f8f6b",
      yellow: "#b6862c",
      blue: "#2f6fed",
      magenta: "#8457d5",
      cyan: "#0f7c91",
      white: "#93a1b5",
      brightBlack: "#708197",
      brightRed: "#de6b71",
      brightGreen: "#55a07f",
      brightYellow: "#c99c42",
      brightBlue: "#5d8ff5",
      brightMagenta: "#9b77eb",
      brightCyan: "#249ab0",
      brightWhite: "#59697b",
    },
    chrome: {
      background: "#e6edf6",
      surface: "#f4f7fb",
      border: "#cad6e4",
      text: "#223042",
      textMuted: "#708197",
      accent: "#2f6fed",
    },
  },
  {
    id: "kinari",
    name: "生成り",
    group: "light",
    description: "和紙・セピア",
    terminal: {
      background: "#fbf3e4",
      foreground: "#4a3b2a",
      cursor: "#b9783a",
      selectionBackground: "#eadabd",
      black: "#efe3ce",
      red: "#b85c4b",
      green: "#6d8f4f",
      yellow: "#b9781f",
      blue: "#4e7dbd",
      magenta: "#9a5cb4",
      cyan: "#3f8f88",
      white: "#a3917b",
      brightBlack: "#8b7b66",
      brightRed: "#d3705f",
      brightGreen: "#83a965",
      brightYellow: "#d4993c",
      brightBlue: "#6d97cf",
      brightMagenta: "#b47ace",
      brightCyan: "#5baaa3",
      brightWhite: "#6d5a47",
    },
    chrome: {
      background: "#efe1c8",
      surface: "#fbf3e4",
      border: "#dcc8a7",
      text: "#4a3b2a",
      textMuted: "#8b7b66",
      accent: "#b9781f",
    },
  },
  {
    id: "geppaku",
    name: "月白",
    group: "light",
    description: "氷色・クリア",
    terminal: {
      background: "#f6fbff",
      foreground: "#24374a",
      cursor: "#2f7db9",
      selectionBackground: "#d6e9ff",
      black: "#ddeaf6",
      red: "#c35a61",
      green: "#4d946f",
      yellow: "#b8862f",
      blue: "#2f7db9",
      magenta: "#7c66d9",
      cyan: "#1f8ea5",
      white: "#8da0b7",
      brightBlack: "#6d8299",
      brightRed: "#db7279",
      brightGreen: "#66ac88",
      brightYellow: "#cf9c46",
      brightBlue: "#5b99d1",
      brightMagenta: "#9984ee",
      brightCyan: "#39a8be",
      brightWhite: "#5f7387",
    },
    chrome: {
      background: "#e5f0f8",
      surface: "#f6fbff",
      border: "#cddded",
      text: "#24374a",
      textMuted: "#6d8299",
      accent: "#2f7db9",
    },
  },
  {
    id: "sakura",
    name: "桜",
    group: "light",
    description: "桜色・やわらかい赤",
    terminal: {
      background: "#fff5f7",
      foreground: "#4c2d38",
      cursor: "#df4d7b",
      selectionBackground: "#ffd7e0",
      black: "#f3dee5",
      red: "#c73c6c",
      green: "#6f9d68",
      yellow: "#c28c35",
      blue: "#6a8bd8",
      magenta: "#df4d7b",
      cyan: "#4ca6a8",
      white: "#a88d97",
      brightBlack: "#8d7681",
      brightRed: "#ea5c8b",
      brightGreen: "#86b47f",
      brightYellow: "#d8a34a",
      brightBlue: "#84a3ec",
      brightMagenta: "#f07ca4",
      brightCyan: "#66bdc0",
      brightWhite: "#745762",
    },
    chrome: {
      background: "#f3e1e7",
      surface: "#fff5f7",
      border: "#ebcad6",
      text: "#4c2d38",
      textMuted: "#8d7681",
      accent: "#df4d7b",
    },
  },
  {
    id: "wakaba",
    name: "若葉",
    group: "light",
    description: "若葉・ミント",
    terminal: {
      background: "#f3fbf5",
      foreground: "#264133",
      cursor: "#2f9a68",
      selectionBackground: "#d5f0de",
      black: "#deeedf",
      red: "#c65d5d",
      green: "#2f9a68",
      yellow: "#ba8e2f",
      blue: "#5087cf",
      magenta: "#8f6ad8",
      cyan: "#2b9cab",
      white: "#93a59a",
      brightBlack: "#72867a",
      brightRed: "#db7373",
      brightGreen: "#51b383",
      brightYellow: "#d2a246",
      brightBlue: "#73a0df",
      brightMagenta: "#a989ea",
      brightCyan: "#4ab6c2",
      brightWhite: "#607568",
    },
    chrome: {
      background: "#e2f0e5",
      surface: "#f3fbf5",
      border: "#c9e2cf",
      text: "#264133",
      textMuted: "#72867a",
      accent: "#2f9a68",
    },
  },
  {
    id: "hakuchuumu",
    name: "白昼夢",
    group: "light",
    description: "パステル・夢色",
    terminal: {
      background: "#fcf8ff",
      foreground: "#473a54",
      cursor: "#c857a6",
      selectionBackground: "#eadcff",
      black: "#ece4f4",
      red: "#c8577f",
      green: "#7a9e73",
      yellow: "#b58a38",
      blue: "#6c7ce0",
      magenta: "#c857a6",
      cyan: "#4ea9c2",
      white: "#a394ad",
      brightBlack: "#857692",
      brightRed: "#de6992",
      brightGreen: "#93b58b",
      brightYellow: "#caa04d",
      brightBlue: "#8895ee",
      brightMagenta: "#dd8cc4",
      brightCyan: "#6bc0d6",
      brightWhite: "#6b5c78",
    },
    chrome: {
      background: "#eee6f6",
      surface: "#fcf8ff",
      border: "#ddd0ec",
      text: "#473a54",
      textMuted: "#857692",
      accent: "#c857a6",
    },
  },
];

const THEME_ALIASES: Record<string, string> = {
  "yoru-cafe": "mayonaka",
  kokuyou: "kyokuya",
  yakei: "ginga",
  kagaribi: "kogane",
  "sumi-iro": "seijaku",
  fuji: "hakuchuumu",
  aozora: "geppaku",
  yuuyake: "kinari",
  hishou: "kyokuya",
  kosho: "kinari",
  usuzumi: "seijaku",
  kinsei: "yogiri",
  kohaku: "kogane",
  kokeniwa: "chikurin",
  "akane-gumo": "yougan",
  hisui: "chikurin",
  tsuyukusa: "geppaku",
};

const THEME_MAP = new Map(THEMES.map((theme) => [theme.id, theme]));

export function resolveThemeId(id?: string | null): string {
  if (id && THEME_MAP.has(id)) {
    return id;
  }

  if (id) {
    const alias = THEME_ALIASES[id];
    if (alias && THEME_MAP.has(alias)) {
      return alias;
    }
  }

  return DEFAULT_THEME_ID;
}

export function getTheme(id: string): ThemeDefinition {
  return THEME_MAP.get(resolveThemeId(id)) ?? THEMES[0];
}