// Japanese UI strings for the Online savepoint panel.
// IMPORTANT: This file is authored by the parent session (UTF-8 safe path).
// Codex/subagents must import from here and must NOT add new Japanese literals elsewhere.

export const onlineStrings = {
  panelTitle: "セーブポイント",
  panelDescription: "このPCに作業の区切りを保存します。必要なときだけ、1件ずつ人へ渡したり受け取ったりできます。",
  trashDescription: "削除したセーブポイントです。元に戻すか、完全に削除できます。",
  viewSwitcherLabel: "セーブポイントの表示切り替え",
  activeView: (count: number): string => `保存済み ${count}`,
  trashView: (count: number): string => `ゴミ箱 ${count}`,
  dragHint: "カードをドラッグして、左右で完全再開・下でこの会話へ引き継ぐ・人へ渡す、を選べます。",
  dragHandleLabel: (summary: string): string =>
    `${summary}の操作を開く。ドラッグすると渡す先を選べます`,
  dragGhostMeta: "左・右端: 完全再開 / 下: この会話へ引き継ぎ / 人に渡す: ファイル作成 / 一覧へ戻す: キャンセル",
  dragDropFullResumeSplit: (direction: "left" | "right"): string =>
    direction === "left" ? "左に完全再開" : "右に完全再開",
  dragGhostPasteTarget: (_agent: string): string => "この会話へ引き継ぎ",
  dragGhostTransferTarget: "人に渡すファイルを作成",
  dragDropPastePreview: (agent: string): string => `ここに${agent}へ引き継ぎ文書を渡します（Enterで送信）`,
  dragDropCwdMissing: "元の作業フォルダが見つからないため、ホームフォルダで新しいセッションを開始しました。引き継ぎ書は絶対パスで参照できます。",
  dragDropInvalidTarget: "ペインの左端・右端（完全再開）、下（引き継ぎ）、または「人に渡す」へドロップしてください。",
  dragDropTargetGone: "ドロップ先のタブまたはペインが変わったため、処理を中止しました。",
  dragDropApprovalBlocked: "確認や選択肢への回答待ちのため、入力欄へ貼り付けませんでした。回答後にもう一度ドロップしてください。",
  dragDropPreparingDraft: "引き継ぎ文を準備しています…",
  dragDropSpawning: "完全再開を準備しています…",
  dragDropTargetNotReady: "ドロップ先のセッションを起動できなかったため、入力欄へ貼り付けませんでした。",
  dragDropPasted: "入力欄へ引き継ぎ文を貼り付けました。Enterで送信してください。",
  dragDropPastedCwdMissing: "入力欄へ引き継ぎ文を貼り付けました。元の作業フォルダは見つかりませんが、引き継ぎ書は絶対パスで参照できます。Enterで送信してください。",
  dragDropSpawned: "新しいペインへ引き継ぎました。",
  dragDropResumed: "新しいペインで完全再開しました。",
  dragDropFullResumeFallback: "完全再開できないため、引き継ぎ書から新しいセッションを開始します。",
  dragDropErrorPrefix: "セーブポイントの処理に失敗しました: ",
  openPanelLabel: "セーブポイントを開く",
  settingsTabLabel: "セーブポイント",
  settingsHeading: "セーブポイント",
  settingsDescription: "普段はこのPCだけに保存し、人へ渡すときだけ受け渡しファイルを作ります。共有フォルダの設定は必要ありません。",
  settingsStorageHeading: "このPCの保存先",
  settingsStorageDescription: "セーブポイントはmycmuxが管理するローカルフォルダへ保存します。",
  settingsStorageSyncHint: "保存先は自動で決まります。別の人へ渡す操作をしても、このフォルダ自体は共有されません。",
  settingsStorageCurrentLabel: "ローカル保存先",
  settingsStorageLoading: "保存先を確認しています…",
  settingsStorageConfigured: "保存先を設定済み",
  settingsStorageUnknown: "保存先を確認できません",
  settingsStorageReadyOnFirstSave: "最初の保存時に作成します",
  settingsLegacyStorageLabel: "以前の保存先",
  settingsLegacyStorageNote: "以前の共有先は変更・削除していません。新しい保存や自動整理には使いません。",
  settingsStorageMoveNote: "以前の共有フォルダは変更しません。そこに残る旧記録は、この画面へ自動では取り込みません。",
  settingsStorageScopeNote: "セーブポイントは会話と引き継ぎ情報の記録です。作業フォルダ全体のバックアップではありません。",
  settingsSaveHeading: "保存する",
  settingsSaveMethodsAriaLabel: "セーブポイントの保存方法",
  settingsStepCurrent: "作業途中",
  settingsStepCurrentDescription: "同じ引き継ぎ記録を更新しながら、いつでも続きを渡せます。",
  settingsStepFinal: "終了時",
  settingsStepFinalDescription: "作業の区切りを、あとから変わらない記録として残します。",
  settingsStepResume: "続きから始める",
  settingsStepResumeDescription: "要点だけ、または会話ごと引き継いで新しい作業を開きます。",
  settingsSeparationNote: "人へ渡すのは選んだセーブポイント1件だけです。作業フォルダ全体は含みません。",
  searchPlaceholder: "記録を検索 (担当者・案件・内容)",
  refresh: "更新",
  receiveTransfer: "受け取る",
  receiveTransferHint: "受け渡しファイルをここへドロップすることもできます",
  shareTransfer: "人に渡す",
  shareTransferDrop: "ここで離して人に渡す",
  shareTransferDropHint: "受け渡しファイルを1つ作ります",
  transferFileType: "mycmux セッション受け渡し",
  transferDefaultFileName: "mycmux-session",
  transferSaveDialogTitle: "セッションの受け渡しファイルを保存",
  transferOpenDialogTitle: "受け渡しファイルを選ぶ",
  transferSaved: "受け渡しファイルを保存しました",
  transferSaveErrorPrefix: "受け渡しファイルを作成できませんでした: ",
  transferReceived: "セーブポイントを受け取りました",
  transferAlreadyReceived: "このセーブポイントは受け取り済みです",
  transferReceiveErrorPrefix: "セーブポイントを受け取れませんでした: ",
  emptyList: "引き継ぎ記録はありません",
  trashEmpty: "ゴミ箱は空です",
  loadError: "一覧を読み込めませんでした",
  trashLoadError: "ゴミ箱を読み込めませんでした。保存済みの記録は引き続き表示しています。",
  updatedAgoHours: "時間前",
  updatedAgoMinutes: "分前",
  updatedJustNow: "たった今",
  pinnedBadge: "ピン留め",
  warningBadge: "パス警告",
  receivedBadge: "受信",
  expiresSoon: "まもなく期限切れ",
  joinSummary: "Claude Codeへ渡す",
  joinCodex: "Codexへ渡す",
  joinFull: "会話ごと続ける",
  joinFullNotice: "会話の記録を引き継いだ新しい作業を開きます",
  pinOn: "ピン留めする",
  pinOff: "ピン留め解除",
  expandCardDetails: "詳細を表示",
  collapseCardDetails: "詳細を閉じる",
  deletedAgo: (ago: string): string => `削除: ${ago}`,
  moveToTrash: "ゴミ箱へ",
  movedToTrash: "ゴミ箱へ移動しました",
  moveToTrashErrorPrefix: "ゴミ箱への移動に失敗: ",
  restore: "元に戻す",
  restoreDone: "セーブポイントを元に戻しました",
  restoreErrorPrefix: "復元に失敗: ",
  deletePermanently: "完全に削除",
  deletePermanentlyConfirm: "本当に完全削除？",
  deletePermanentlyDone: "完全に削除しました",
  deletePermanentlyErrorPrefix: "完全削除に失敗: ",
  cleanupDone: "期限切れの記録を整理しました",
  joinCwdMissing: "元の作業フォルダが見つからないため、ホームフォルダで開きました。作業ファイルは含まれません。",
  // The pasted draft has its newlines collapsed to spaces by
  // sanitizeSavepointHandoffDraft, so this must read naturally as one line.
  // Keep it free of half-width ()<>|&;$` too: the draft lands in an input box
  // without a trailing Enter, and if the pane turns out to be a plain shell the
  // operator's Enter would otherwise produce a bash syntax error.
  // Do not name a specific tool either — Claude has Read, Codex does not.
  joinPrompt: (handoffPath: string): string =>
    `引き継ぎ書 ${handoffPath} を読んでください。読んだら、①何の作業か（目的と現在地）②前提・制約 ③未確定・要確認の点 ④そのまま進める場合の次の一手（案） の4点だけを簡潔に提示し、そこで止まってこちらの指示を待ってください。指示があるまでファイルの変更・コマンド実行はしないでください。`,
  turnsSuffix: "往復",
  filesSuffix: "ファイル変更",
  // --- publish (pane tab bar) ---
  publishButtonTitleNew: "セーブポイントを作成",
  publishButtonTitleUpdate: "セーブポイントを更新",
  publishDialogTitleNew: "セーブポイントを作成",
  publishDialogTitleUpdate: "セーブポイントを更新",
  publishSummaryLabel: "記録の見出し",
  publishSummaryPlaceholder: "空欄なら最後の指示から自動生成",
  publishConfirmNew: "ここまでを保存",
  publishConfirmUpdate: "保存内容を更新",
  finalizeConfirm: "終了時の記録を残す",
  finalizeHint: "この時点を変更しない記録として残します。作業画面は閉じません。",
  publishCancel: "キャンセル",
  publishInProgress: "保存中…",
  publishSuccessNew: "引き継ぎ記録を保存しました",
  publishSuccessUpdate: "引き継ぎ記録を更新しました",
  finalizeSuccess: "終了時の記録を残しました",
  publishErrorPrefix: "保存に失敗しました: ",
  publishNoTranscript: "まだこの作業の会話ログがありません。1往復してから保存してください。",
  publishWarningsSuffix: "件のパス警告 (相手側にない可能性があります)",
  publishNoSession: "この作業IDがまだ確定していません。エージェント起動後にもう一度お試しください。",
  // --- entry provenance (Online panel) ---
  badgeOpenHere: "このPCで開いている作業",
  badgeExpired: "期限切れ間近",
  sessionIdPrefix: "作業ID ",
  recordCurrentBadge: "作業途中",
  recordClosedBadge: "終了済み",
  recordFinalBadge: "終了時",
  // --- publish progress (popover / panel) ---
  publishProgressTitle: "引き継ぎ記録を保存しています",
  publishProgressHint: "数秒〜十数秒かかります",
  publishStepDigest: "会話履歴を読み取り・要約",
  publishStepHandoff: "引き継ぎ書 (handoff.md) を生成",
  publishStepBundle: "引き継ぎ記録を作成",
  publishStepRegister: "一覧へ登録",
  publishStepDone: "完了",
  publishResultLocationLabel: "保存先",
  publishResultModeNew: "新しい作業途中の記録を保存",
  publishResultModeUpdate: "作業途中の記録を更新",
  publishResultModeFinal: "終了時の記録を保存",
  // --- local sessions section (Online panel publish path) ---
  panelLocalSessionsEmpty: "現在開いているエージェントの作業はありません",
  panelLocalSessionsHint: "ここから引き継ぎ記録を保存できます (ペイン右上のしおりボタンと同じ動作)",
  panelPublishButton: "ここまでを保存",
  panelPublishButtonUpdate: "保存内容を更新",
  panelSessionNoId: "作業ID確定待ち",
  // --- local sessions: status & meta (v0.13.3) ---
  badgeDormant: "未起動",
  badgeDormantHint: "ペインは未起動ですが、保存済みの会話履歴から引き継ぎ記録を作成できます",
  statusWorking: "実行中",
  statusWaiting: "入力待ち",
  statusIdle: "待機中",
  lastPublishedPrefix: "最終保存 ",
  notPublishedYet: "まだ保存なし",
  branchTitle: "git ブランチ",
  workspaceTitle: "ワークスペース",
  // --- local sessions: collapsible footer (v0.14) ---
  panelLocalSessionsHeaderTitle: "このPCの作業",
  panelLocalSessionsToggleAriaLabel: "このPCの作業一覧の開閉",
  panelLocalSessionsWorkingCountTitle: (count: number): string => `実行中 ${count}件`,
  panelLocalSessionsWaitingCountTitle: (count: number): string => `入力待ち ${count}件`,
  panelLocalSessionsCardOpenHint: "クリックしてこのペインへ移動します",
  panelLocalSessionsCardOpenUnavailable: "ペインが未起動のため開けません",
} as const;

export type OnlineStrings = typeof onlineStrings;
