export const agentDesignStrings = {
  title: "エージェント設計", close: "閉じる", dismiss: "知らせを閉じる", refresh: "読み直す",
  views: ["概要", "読み方", "比べる", "点検"], search: "エージェント設計を探す", searchPlaceholder: "設定・文書・スキルを探す",
  services: "サービス", thisPc: "この PC", chooseFolder: "作業フォルダを選んで見る", folder: "作業フォルダ",
  home: "ホームで見る", back: "戻る", backOverview: "概要へ戻る", openSkills: "スキルを開く",
  noData: "目録を読み込んでいます", absent: "無し", unknown: "不明", notCounted: "数えない", unsupported: "未対応",
  readOnly: "読むだけ", noResults: "一致する項目はありません", noItems: "この層の項目はありません",
  noDocument: "本文は出しません。確認できる名前と数、秘密でない項目を表示します。",
  loadingDocument: "文書を読んでいます", documentError: "この文書を表示できません。読み直して確認してください。",
  error: "読み直しに失敗しました。前回の目録を表示しています。", cacheError: "前回の目録は取得できませんでした。",
  countError: "読み取れない項目があります。値は「不明」として表示します。",
  stageC: "直す案と本体の変更は段 C で作ります。", stageB: "履歴と書き出しは段 B で作ります。",
  refreshed: "読み直しました", updating: "読み直し中", version: "版", updatedAt: "読み直し", charsUnit: "字", linesUnit: "行", filesUnit: "本",
  everyRead: "毎回読む量", unknownTotal: "一部は不明", productNotCounted: "製品の組み込みの指示と道具の説明は数えない", productAdded: "記録で確認した製品が足す節",
  sessionOrigin: "に始まった会話の始めの部分から数えた", sessionStartUnknown: "会話の始まった時刻は不明",
  partialTotal: "確認できた分", layers: "設計の層", contents: "中身", location: "置き場所", reading: "読み方", links: "つながり",
  details: "選んだ層の中身", readDocument: "中身を読む", source: "根拠", document: "文書", rules: "規則", pathMatch: "paths が一致したとき",
  layerNote: "下が生身の本体。上へいくほど自分で積んだもの。カードを押すと右に中身が出る。",
  legend: "読まれる時期の札", crossLinks: "サービスの間のつながり", noLinks: "つながりの宣言はありません",
  noTarget: "行き先がありません", overridden: "同じフォルダの AGENTS.override.md が先に読まれます",
  inputParts: ["指示", "記憶の索引", "スキルの一覧", "起動のフックの出力"],
  layerNames: ["", "本体（生身）", "実行の設定と権限", "指示とルール", "記憶と記録", "道具と手順", "自動化", "参照資料と設計"],
  layerNotes: ["", "生身", "起動のとき", "会話の始めと場面", "索引だけを毎回読む", "名前と説明を先に読む", "場面と時刻で動く", "指示から参照"],
  timings: { always: "毎回", conditional: "条件つき", onDemand: "必要なとき", event: "場面ごと", schedule: "時刻で", outside: "文脈の外", private: "中身は出さない" } as Record<string, string>,
  timingHelp: { always: "会話の始めに文脈へ入る", conditional: "フォルダや paths が合ったとき", onDemand: "呼ばれた・開かれた分", event: "決まった場面で動く", schedule: "決まった時刻に動く", outside: "文脈には入らない", private: "名前を伏せ、数と大きさだけ" } as Record<string, string>,
  evidence: { measured: "実測", product: "製品の決まり", declaration: "宣言", estimated: "推定", unknown: "不明" } as Record<string, string>,
  flowTitle: "起動から会話の終わりまで", flowHelp: "設定と規則の宣言から組み立て、始めの記録で確認できた分に「記録で確認」を付けます。",
  recorded: "記録で確認", declared: "宣言から", stages: ["起動", "会話の始め", "依頼のたび", "道具のたび", "必要なとき", "応答のたび", "会話の終わり"],
  flowNames: ["設定を読む", "指示を探して読む", "記憶の索引を読む", "スキルの一覧を受け取る", "SessionStart のフック", "依頼のフック", "道具の前後のフック", "条件つきの規則", "スキルの本文と台本", "参照資料と記憶の本文", "Stop のフック", "SessionEnd のフック"],
  codexFlowNames: ["設定を読む", "AGENTS.md の連なりと override", "記憶の節を読む", "スキルの一覧を受け取る", "SessionStart のフック", "依頼のフック", "道具の前後のフック", "追加の指示", "明示して呼ぶスキル", "参照資料と記憶の本文", "応答後のフック", "会話の終わりのフック"],
  parts: "毎回読む量の内訳", listingParts: "スキルの一覧の内訳", reductions: "減らせそうなところ", noReduction: "記録から確認できる候補はありません",
  scenario: "場面を変えて見る", touchedPath: "触るパス", touchedPathPlaceholder: "例: src/example.tsx", checkScenario: "条件を照らす", scenarioNote: "paths の宣言との一致を示します。実際に読まれた回数は数えません。",
  conditionalAdded: "条件つきで足される", noConditional: "一致する条件つきの規則はありません",
  groupNames: { own: "自分のスキル", user: "自分のスキル", builtin: "製品の同梱ほか", system: "製品の同梱", synced: "claude.ai の同期", command: "コマンド", plugin: "プラグイン", unknown: "出どころは不明" } as Record<string, string>,
  compareTitle: "同じ働きのものを横に並べる", compareHelp: "行を押すと、許した文書の本文や秘密でない設定を並べて開きます。Hermes は名前と置き場所だけです。",
  sameRole: "同じ働き", differentForm: "形が違う", differentCount: "数が違う", claudeOnly: "Claude だけ", damaged: "傷あり", compareTag: "見比べ",
  compareRows: ["共通の指示", "フォルダの指示", "規則", "実行の設定", "実行の許可", "記憶", "自分のスキル", "スキルの一覧", "プラグイン", "サブエージェント", "MCP", "フック", "定期のジョブ", "参照資料"],
  inspectTitle: "設計の点検", inspectHelp: "置き場所・設定・始めの会話記録を照らして出します。意図した形は、理由と日付を残して閉じます。",
  noFindings: "確認できる指摘はありません", closedCount: "意図どおりとして閉じたもの", repair: "直す", decide: "決める", watch: "見ておく",
  proposal: "直す案", investigate: "調べる", open: "開く", closeIntentional: "意図どおりとして閉じる", reason: "理由", reasonPlaceholder: "意図した設計である理由を書く",
  saveClose: "理由を残して閉じる", cancel: "戻る", closed: "理由と日付を残して閉じました", closeError: "指摘を閉じられませんでした。読み直して確認してください。",
  unknowns: "分かっていないこと", proposalText: "直す案の説明", evidenceFiles: "根拠のファイルと記録", candidateSkills: "一覧から外す候補を選ぶ", selectedCandidates: "選んだ候補",
  noUncertainty: "この指摘で追加の不明点はありません", hermesScope: "Hermes は名前と置き場所だけを確認します", hermesLocation: "Hermes の場所を足す",
  refreshedDuration: "読み直しの所要時間", consumedRecords: "読んだ記録の行数", stoppedAt: "読むのを止めた所", modified: "更新日時", enabled: "有効", disabled: "無効", mcpCommented: "コメントで止めた",
  kinds: { runtime: "本体と組み込み", plugins: "プラグイン", mcp: "MCP", scheduled: "定期のジョブ", skillListing: "スキルの一覧", privateCount: "鍵のファイル（数だけ）", settings: "実行の設定", settingsLocal: "ローカルの設定", permissionRules: "実行の許可（大きさだけ）", hooks: "フックの登録", memoryDirectory: "記憶の場所", cron: "定期のジョブの場所" } as Record<string, string>,
  fieldNames: { sourceKind: "出どころ", matcher: "対象の条件", model: "モデル", effortLevel: "考える量", model_reasoning_effort: "考える量", approval_policy: "承認", sandbox_mode: "実行の範囲", personality: "振る舞い", defaultMode: "既定の許可", allowCount: "許可の数", envCount: "環境変数（数だけ）", unsupported: "未対応の項目", count: "数", enabled: "有効", version: "版", productInstructions: "製品の指示", name: "名前", catalogId: "スキル目録の ID", allowImplicitInvocation: "暗黙の呼び出し", implicitSettingPath: "暗黙の呼び出しの設定", implicitSettingLine: "設定の行", targetExists: "行き先の有無", chars: "字数", lines: "行数", charLimit: "字数の上限", lineLimit: "行数の上限" } as Record<string, string>,
  findingTitles: { disabledPlugins: "設定で切ったプラグインのスキルが一覧に載る", unusedListing: "使われた記録の無いスキルが毎回の一覧に載る", implicitHidden: "自分のスキルが一覧に載らない", shadowedAgents: "AGENTS.override.md があるため AGENTS.md は読まれない", memoryLimit: "MEMORY.md が上限に近い", duplicate: "同じ名前のスキルが複数の置き場所にある", brokenTarget: "入口の行き先が無い" } as Record<string, string>,
  uncertaintyNames: { pluginDisableReason: "設定で切ったものが載る理由は未確認です。", recordMayBeOlder: "記録は現在の設定より古い可能性があります。", usageStartDate: "使用記録を数え始めた日は不明です。", absenceIsNotNonUse: "記録が無いことは、使っていない証明にはなりません。", explicitInvocationStillAvailable: "$名前で明示したときの呼び出しは別です。", otherReadersUnknown: "ほかにこのファイルを読む道具があるかは未確認です。" } as Record<string, string>,
  proposals: { disabledPlugins: "設定と一覧の読み元を調べ、差分の案を作り、次の会話の一覧で照らします。", unusedListing: "中身を見ながら候補を選び、段 C で一覧から外す案を作ります。", implicitHidden: "暗黙の呼び出しを切った意図を確認します。意図した形なら理由を残して閉じられます。", shadowedAgents: "生成元と override の意図を確認します。同期を止める変更は段 C で扱います。", memoryLimit: "索引のうち必要な部分を残し、本文に移す差分の案を段 C で作ります。", duplicate: "本体・入口・写しの関係を確認してから、整理する案を段 C で作ります。", brokenTarget: "本体の場所と入口の宣言を確認し、行き先を直す案を段 C で作ります。" } as Record<string, string>,
  ruleNames: { disabledButListed: "設定の enabled と、始めの一覧を照合", noUsageRecord: "skillUsage に名前の記録が無い", implicitInvocationDisabled: "allow_implicit_invocation が false", overridePrecedence: "同じフォルダの override が優先", declaredWriter: "links.json が書き先を宣言", memoryLimit: "上限 200 行・25,000 字", missingWrapperTarget: "入口が宣言した本体が存在しない", sameSkillName: "同じサービスに同じ名前がある" } as Record<string, string>,
  relationNames: { executes: "場面から台本へ", references: "文書から参照", readsSource: "入口から本体へ", shadows: "override が先に読まれる", declaredCall: "宣言された呼び出し", generates: "宣言された書き先" } as Record<string, string>,
  stopNames: { firstAssistant: "最初の assistant の前", firstRequest: "最初の依頼の本文の前", worldState: "world_state の本文の前", lineLimit: "行数の上限", byteLimit: "大きさの上限", eof: "ファイルの終わり", unsupported: "未対応の形", unavailable: "記録を取得できない" } as Record<string, string>,
} as const;
export function number(value: number | null | undefined) { return value == null ? agentDesignStrings.unknown : value.toLocaleString("ja-JP"); }
export function chars(value: number | null | undefined) { return value == null ? agentDesignStrings.unknown : number(value) + " " + agentDesignStrings.charsUnit; }
export function count(value: number | null | undefined) { return value == null ? agentDesignStrings.unknown : number(value) + " " + agentDesignStrings.filesUnit; }
export function bytes(value: number | null | undefined) { return value == null ? agentDesignStrings.unknown : value >= 1024 * 1024 ? (value / 1024 / 1024).toFixed(2) + " MB" : value >= 1024 ? (value / 1024).toFixed(1) + " KB" : value + " B"; }
