export const agentDesignStrings = {
  title: "エージェント設計", close: "閉じる", dismiss: "知らせを閉じる", refresh: "読み直す",
  views: ["しくみ", "概要", "読み方", "比べる", "点検"], search: "エージェント設計を探す", searchPlaceholder: "設定・文書・スキルを探す",
  services: "サービス", thisPc: "この PC", chooseFolder: "作業フォルダを選んで見る", folder: "作業フォルダ",
  home: "ホームで見る", back: "戻る", backOverview: "元の画面へ戻る", openSkills: "スキルを開く",
  noData: "目録を読み込んでいます", absent: "無し", unknown: "不明", notCounted: "数えない", unsupported: "未対応",
  readOnly: "読むだけ", noResults: "一致する項目はありません", noItems: "この層の項目はありません",
  documentFiles: "ファイル", parentFolder: "上のフォルダ", moreFiles: "次のファイル", maskedFile: "値を伏せる",
  showSecret: "表示", hideSecret: "隠す", loadingSecret: "取得中", emptySecret: "空",
  secretError: "値を取得できません。文書を読み直してください。", maskedValues: "伏せた値",
  secretsNotice: "鍵らしい値は伏せています。表示を押した値だけを一時表示し、15秒後・画面を離れたときに伏せ直します。",
  truncatedDocument: "2MiB を超えるため先頭だけを表示しています。全体の大きさ",
  documentReasons: {
    fileMissing: "ファイルがありません。", fileUnreadable: "ファイルを読む権限がないか、読み取りに失敗しました。",
    notAFile: "通常のファイルではありません。", binaryFile: "バイナリ形式のため文字として表示できません。",
    unsupportedEncoding: "UTF-8・UTF-16 で読み取れない文字コードです。", outsideFolder: "この項目のフォルダの外を指すため開けません。",
    compiledProduct: "製品に組み込まれた本文を公開するファイルはありません。設定と関連ファイルを選んで開けます。",
    scheduledUnavailable: "時刻で動く処理の登録を取得できません。関連ファイルを選んで開けます。",
  } as Record<string, string>,
  renderedDocument: "読みやすい表示", sourceDocument: "原文", documentDisplay: "文書の表示", documentToc: "目次", documentMetadata: "文書の情報",
  loadingDocument: "文書を読んでいます", documentError: "この文書を表示できません。読み直して確認してください。",
  error: "読み直しに失敗しました。前回の目録を表示しています。", cacheError: "前回の目録は取得できませんでした。",
  countError: "読み取れない項目があります。取得できた情報を表示しています。",
  stageC: "直す案と本体の変更は段 C で作ります。", stageB: "履歴と書き出しは段 B で作ります。",
  refreshed: "読み直しました", updating: "読み直し中", version: "版", updatedAt: "読み直し", charsUnit: "字", linesUnit: "行", filesUnit: "本",
  everyRead: "初期情報の記録", unknownTotal: "合計の一部は未計測", productNotCounted: "製品の組み込みの指示と道具の説明は別の量", productAdded: "記録で確認した製品が足す節",
  sessionOrigin: "に始まった会話の始めの部分から数えた", sessionStartUnknown: "会話の始まった時刻は不明",
  partialTotal: "確認できた分", layers: "設計の層", contents: "中身", location: "置き場所", reading: "読み方", links: "つながり",
  details: "選んだ層の中身", readDocument: "中身を読む", source: "根拠", document: "文書", rules: "規則", pathMatch: "paths が一致したとき",
  layerNote: "層を選んで、役割と中身を確認できます。",
  legend: "読まれる時期の札", crossLinks: "サービスの間のつながり", noLinks: "つながりの宣言はありません",
  noTarget: "行き先がありません", overridden: "同じフォルダの AGENTS.override.md が先に読まれます",
  inputParts: ["指示", "記憶の索引", "スキルの一覧", "起動のフックの出力"],
  layerNames: ["", "本体", "実行設定と権限", "指示とルール", "記憶と記録", "道具と手順", "自動化", "参照資料と設計"],
  layerNotes: ["", "AI を動かす製品", "起動のとき", "会話の始めと場面", "索引だけを毎回読む", "名前と説明を先に読む", "場面と時刻で動く", "指示から参照"],
  timings: { always: "毎回読む", conditional: "条件つき", onDemand: "呼ばれたときだけ", event: "出来事ごと", schedule: "時刻で", outside: "会話には入らない", private: "値を伏せる" } as Record<string, string>,
  timingHelp: { always: "会話の始めに入る情報（設定上の読み方）", conditional: "作業場所やファイルの条件が合ったとき", onDemand: "呼ばれた・開かれた本文だけを追加", event: "決まった出来事で動く処理", schedule: "決まった時刻に動く処理", outside: "会話には入らない（アプリが使う設定）", private: "鍵らしい値を伏せて開く。押した値だけをその場で表示" } as Record<string, string>,
  evidence: { measured: "取得した情報で確認", product: "製品の決まり", declaration: "設定から分かる", estimated: "推定", unknown: "根拠は未取得" } as Record<string, string>,
  flowTitle: "起動から会話の終わりまで", flowHelp: "設定から分かる読む順序と、初期記録で確認できた情報を分けます。",
  recorded: "記録で確認", declared: "設定から分かる", stages: ["起動", "会話の始め", "依頼のたび", "道具のたび", "必要なとき", "応答のたび", "会話の終わり"],
  flowNames: ["設定を読む", "指示を探して読む", "記憶の索引を読む", "スキルの一覧を受け取る", "会話の始めの自動処理", "依頼に伴う自動処理", "道具の前後の自動処理", "条件つきの規則", "スキルの本文と台本", "参照資料と記憶の本文", "返事に伴う自動処理", "会話の終わりの自動処理"],
  codexFlowNames: ["設定を読む", "作業場所の指示と優先する文書", "記憶の節を読む", "スキルの一覧を受け取る", "会話の始めの自動処理", "依頼に伴う自動処理", "道具の前後の自動処理", "追加の指示", "明示して呼ぶスキル", "参照資料と記憶の本文", "返事に伴う自動処理", "会話の終わりの自動処理"],
  parts: "初期情報の内訳", listingParts: "スキルの一覧の内訳", reductions: "減らせそうなところ", noReduction: "記録から確認できる候補はありません",
  scenario: "場面を変えて見る", touchedPath: "触るパス", touchedPathPlaceholder: "例: src/example.tsx", checkScenario: "条件を照らす", scenarioNote: "paths の宣言との一致を示します。実際に読まれた回数は数えません。",
  conditionalAdded: "条件つきで足される", noConditional: "一致する条件つきの規則はありません",
  groupNames: { own: "自分のスキル", user: "自分のスキル", builtin: "製品の同梱ほか", system: "製品の同梱", synced: "claude.ai の同期", command: "コマンド", plugin: "プラグイン", unknown: "出どころは不明" } as Record<string, string>,
  compareTitle: "同じ働きのものを横に並べる", compareHelp: "行を押すと、中身を並べて開きます。鍵らしい値は伏せ、押した値だけを表示します。",
  sameRole: "同じ働き", differentForm: "形が違う", differentCount: "数が違う", claudeOnly: "Claude だけ", damaged: "傷あり", compareTag: "見比べ",
  compareRows: ["共通の指示", "フォルダの指示", "規則", "実行の設定", "実行の許可", "記憶", "自分のスキル", "スキルの一覧", "プラグイン", "サブエージェント", "MCP", "フック", "定期のジョブ", "参照資料"],
  inspectTitle: "設計の点検", inspectHelp: "置き場所・設定・始めの会話記録を照らして出します。意図した形は、理由と日付を残して閉じます。",
  noFindings: "確認できる指摘はありません", closedCount: "意図どおりとして閉じたもの", repair: "直す", decide: "決める", watch: "見ておく",
  proposal: "直す案", investigate: "調べる", open: "開く", closeIntentional: "意図どおりとして閉じる", reason: "理由", reasonPlaceholder: "意図した設計である理由を書く",
  saveClose: "理由を残して閉じる", cancel: "戻る", closed: "理由と日付を残して閉じました", closeError: "指摘を閉じられませんでした。読み直して確認してください。",
  unknowns: "分かっていないこと", proposalText: "直す案の説明", evidenceFiles: "根拠のファイルと記録", candidateSkills: "一覧から外す候補を選ぶ", selectedCandidates: "選んだ候補",
  noUncertainty: "この指摘で追加の不明点はありません", hermesScope: "Hermes の設定・指示・記憶・スキル・定期実行を開けます", hermesLocation: "Hermes の場所を足す",
  refreshedDuration: "読み直しの所要時間", consumedRecords: "読んだ記録の行数", stoppedAt: "読むのを止めた所", modified: "更新日時", enabled: "有効", disabled: "無効", mcpCommented: "コメントで止めた",
  kinds: { runtime: "本体と組み込み", plugins: "プラグイン", mcp: "MCP", scheduled: "定期のジョブ", skillListing: "スキルの一覧", privateCount: "鍵のファイル", settings: "実行の設定", settingsLocal: "ローカルの設定", permissionRules: "実行の許可", hooks: "フックの登録", memoryDirectory: "記憶の場所", cron: "定期のジョブの場所" } as Record<string, string>,
  fieldNames: { sourceKind: "出どころ", matcher: "対象の条件", model: "モデル", effortLevel: "考える量", model_reasoning_effort: "考える量", approval_policy: "承認", sandbox_mode: "実行の範囲", personality: "振る舞い", defaultMode: "既定の許可", allowCount: "許可の数", envCount: "環境変数（数だけ）", unsupported: "未対応の項目", count: "数", enabled: "有効", version: "版", productInstructions: "製品の指示", name: "名前", catalogId: "スキル目録の ID", allowImplicitInvocation: "暗黙の呼び出し", implicitSettingPath: "暗黙の呼び出しの設定", implicitSettingLine: "設定の行", targetExists: "行き先の有無", chars: "字数", lines: "行数", charLimit: "字数の上限", lineLimit: "行数の上限" } as Record<string, string>,
  findingTitles: { disabledPlugins: "設定で切ったプラグインのスキルが一覧に載る", unusedListing: "使われた記録の無いスキルが毎回の一覧に載る", implicitHidden: "自分のスキルが一覧に載らない", shadowedAgents: "AGENTS.override.md があるため AGENTS.md は読まれない", memoryLimit: "MEMORY.md が上限に近い", duplicate: "同じ名前のスキルが複数の置き場所にある", brokenTarget: "入口の行き先が無い" } as Record<string, string>,
  uncertaintyNames: { pluginDisableReason: "設定で切ったものが載る理由は未確認です。", recordMayBeOlder: "記録は現在の設定より古い可能性があります。", usageStartDate: "集計を始めた日は未確認です。", absenceIsNotNonUse: "記録が無いことは、使っていない証明にはなりません。", explicitInvocationStillAvailable: "$名前で明示したときの呼び出しは別です。", otherReadersUnknown: "ほかにこのファイルを読む道具があるかは未確認です。" } as Record<string, string>,
  proposals: { disabledPlugins: "設定と一覧の読み元を調べ、差分の案を作り、次の会話の一覧で照らします。", unusedListing: "本文と記録の範囲を確認して、初期の一覧から外す候補を選びます。", implicitHidden: "暗黙の呼び出しを切った意図を確認します。意図した形なら理由を残して閉じられます。", shadowedAgents: "生成元と override の意図を確認します。同期を止めるかは生成元の設定を確認して判断します。", memoryLimit: "索引に必要な案内を残し、詳しい内容を別の本文へ移す案です。", duplicate: "本体・入口・写しの関係を確認して、重複を整理する案を検討します。", brokenTarget: "本体の場所と入口の設定を確認して、行き先を直す案を検討します。" } as Record<string, string>,
  ruleNames: { disabledButListed: "設定の enabled と、始めの一覧を照合", noUsageRecord: "skillUsage に名前の記録が無い", implicitInvocationDisabled: "allow_implicit_invocation が false", overridePrecedence: "同じフォルダの override が優先", declaredWriter: "links.json が書き先を宣言", memoryLimit: "上限 200 行・25,000 字", missingWrapperTarget: "入口が宣言した本体が存在しない", sameSkillName: "同じサービスに同じ名前がある" } as Record<string, string>,
  relationNames: { executes: "場面から台本へ", references: "文書から参照", readsSource: "入口から本体へ", shadows: "override が先に読まれる", declaredCall: "宣言された呼び出し", generates: "宣言された書き先" } as Record<string, string>,
  stopNames: { firstAssistant: "最初の assistant の前", firstRequest: "最初の依頼の本文の前", worldState: "world_state の本文の前", lineLimit: "行数の上限", byteLimit: "大きさの上限", eof: "ファイルの終わり", unsupported: "未対応の形", unavailable: "記録を取得できない" } as Record<string, string>,
} as const;
export function number(value: number | null | undefined) { return value == null ? agentDesignStrings.unknown : value.toLocaleString("ja-JP"); }
export function chars(value: number | null | undefined) { return value == null ? agentDesignStrings.unknown : number(value) + " " + agentDesignStrings.charsUnit; }
export function count(value: number | null | undefined) { return value == null ? agentDesignStrings.unknown : number(value) + " " + agentDesignStrings.filesUnit; }
export function bytes(value: number | null | undefined) { return value == null ? "大きさは未計測" : value >= 1024 * 1024 ? (value / 1024 / 1024).toFixed(2) + " MB" : (value / 1024).toLocaleString("ja-JP", { maximumFractionDigits: 2 }) + " KB"; }
